Feature abc 475 add is loading to progress circle
avonni/base-components pull request #265
Opened 2022-02-21 19:15 UTC by Tinkerled

Added a loading animation that spins while isLoading is true.

2022-02-21 19:46 UTC, nawel-aa requested changes
Works well! It's mostly issues with conventions. 

Two more things, though:
- `is-loading` should be added to the [Progress Circle Confluence page](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1424097342/Progress+Circle).
- The tests should be updated to include tests for `isLoading`.

2022-02-21 19:46 UTC, nawel-aa commented on src/modules/base/progressCircle/__docs__/progressCircle.stories.js
> +        isLoading: {
Also, a loading example could be added to the examples (storybook's and the ones we use in our doc), since it's a pretty cool feature. :)

2022-02-21 19:46 UTC, nawel-aa commented on src/modules/base/progressCircle/progressCircle.css
> +.avonni-progress-circle_dots {
By convention, in the class name, we normally use two `_` between the name of the component and the element. Else it means that `dots` is a modifier, not an element of the component. See the [doc](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587118095/CSS#Class-naming) for more examples.

2022-02-21 19:46 UTC, nawel-aa commented on src/modules/base/progressCircle/progressCircle.js
> -            validValues: TITLE_POSITIONS.valid
We want to keep the `validValues`.

2022-02-21 19:46 UTC, nawel-aa commented on src/modules/base/progressCircle/progressCircle.js
> +     * @type {boolean}
- We miss the `@default false` in the JSDoc comment block (for all documentation on how to write JSDoc comments, check out the [doc](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc)).
- We usually write all the `get()`/`set()` below the declarations of all properties that don't have a `get()`/`set()`(so below `_dots = 1;` in this case).

2022-02-21 19:46 UTC, nawel-aa commented on src/modules/base/progressCircle/progressCircle.js
> +    @api
The `@api` decorator is used only for public properties, that are customizable depending on the context the component is used in.

2022-02-21 20:10 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.js
> -            validValues: TITLE_POSITIONS.valid
Why did I do that 🤷‍♂️

2022-02-21 20:10 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.js
> +    @api
Got it 👌

2022-02-21 20:17 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.js
> +     * @type {boolean}
Makes sense thanks!

2022-02-21 20:26 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.css
> +.avonni-progress-circle_dots {
👍

2022-02-21 21:15 UTC, Tinkerled commented on src/modules/base/progressCircle/__docs__/progressCircle.stories.js
> +        isLoading: {
Added:
- Base Loading
- Base With Thickness X-Small Loading
- Drain Loading
- Extra Small Loading
- Base With Thickness X-Small Loading
- ExtraLarge Loading

2022-02-22 19:03 UTC, nawel-aa requested changes
`is-loading` should still be added to the [Progress Circle Confluence page](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1424097342/Progress+Circle).

2022-02-22 19:03 UTC, nawel-aa commented on src/modules/base/progressCircle/progressCircle.js
> +    @api
The `@api` needs to be removed here too.

2022-02-22 21:29 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.js
> +    @api
Thanks

2022-02-22 21:29 UTC, Tinkerled commented on src/modules/base/progressCircle/progressCircle.html
> +    <span class={progressLabelClass}> </span>
🤔 weird things happen in my commits lol

2022-02-22 21:32 UTC, Tinkerled commented on src/modules/base/progressCircle/__tests__/progressCircle.test.js
> +                '.avonni-progress-circle__dots'
Useful

2022-02-22 21:32 UTC, Tinkerled commented
Documentation added

2022-03-08 13:32 UTC, merged