[feat] (ABC-489): Add and improve list styling hooks
avonni/base-components pull request #266
Opened 2022-02-25 15:40 UTC by Tinkerled

-  repurpose --avonni-list-item-color-background to basic item background
- --avonni-list-item-sortable-color-background
- --avonni-list-item-non-sortable-hover-color-background
- --avonni-list-item-spacing
- --avonni-list-item-block-start
- --avonni-list-item-block-end
- --avonni-list-item-inline-start
- --avonni-list-item-inline-end
- remove unused --avonni-list-item-cursor
- --avonni-list-item-sortable-cursor
- --avonni-list-item-non-sortable-cursor

2022-02-25 16:28 UTC, nawel-aa requested changes
See also my comments on Jira's ABC-490 and ABC-489.

2022-02-25 16:28 UTC, nawel-aa commented on src/modules/base/list/list.css
> +    margin-bottom: var(--avonni-list-item-spacing);
Maybe `--avonni-list-item-spacing-block-between`, to follow the block/inline convention?

2022-02-25 16:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +                /**
I agree that you should remove this class.

2022-02-25 16:28 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @type sizing
The type would be spacing when it's margin/padding. Sizing is used for widths and heights.

2022-03-01 20:16 UTC, nawel-aa requested changes
Works like a charm, but after a second careful review, there are some naming and doc changes to make. 🙂

2022-03-01 20:16 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @type styling
I think the type is supposed to be a [CSS data type](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types). So I would go with "string" for the cursors, since nothing else seems to fit.

2022-03-01 20:16 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @name --avonni-list-item-color-background-hover-sortable
After talking with Renaud, I think that since "sortable" can be used with "hover", it should be considered an attribute and not a state. So according to the naming convention, it would be `--avonni-list-item-color-background-sortable-hover`.

2022-03-08 14:37 UTC, lgilmet commented
Hooks renamed and tested.

2022-03-08 14:43 UTC, lgilmet commented
Hook type spacing changed to dimension

2022-03-08 15:28 UTC, nawel-aa approved these changes

2022-03-09 14:23 UTC, merged