[feat] (ABC-478): Add brand variant to button menu and tests
avonni/base-components pull request #275
Opened 2022-03-10 15:05 UTC by lgilmet

2022-03-10 15:17 UTC, nawel-aa requested changes
Right now the storybook config stories are useless because they are not linked to the wrappers. You should fix the storybook wrappers (`storybookWrappers > buttonMenu`) and check again if the brand variant is working. 😉

2022-03-10 17:09 UTC, nawel-aa commented on src/modules/base/buttonMenu/buttonMenu.js
> +                ('container' || 'bare-inverse' || 'border-inverse');
This refactor doesn't work, see previous comment.

2022-03-10 17:13 UTC, nawel-aa commented on src/modules/base/buttonMenu/buttonMenu.js
> +        return !(this.iconName === ('utility:down' || 'utility:chevrondown'));
This refactor doesn't work, see previous comment.

2022-03-10 17:18 UTC, nawel-aa commented on src/modules/base/storybookWrappers/buttonMenu/base.js
> +    @api click;
We don't need to add the methods in this case, since we never call them from the `.stories.js` file (same for the other wrapper).

2022-03-10 18:07 UTC, lgilmet commented on src/modules/base/buttonMenu/buttonMenu.js
> +        const isBare = this.variant === ('bare' || 'bare-inverse');
🤦‍♂️

2022-03-10 18:39 UTC, lgilmet commented on src/modules/base/buttonMenu/buttonMenu.js
> +        const isBare = this.variant === ('bare' || 'bare-inverse');
I felt real smart too

2022-03-11 16:05 UTC, nawel-aa reviewed
Everything works! 👍 I suggest you add a test (see my comment), and maybe some stories and examples for our website?
Also, don't forget to update Confluence!

2022-03-15 13:44 UTC, lgilmet commented on src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
> +    it('Button menu variant brand without label', () => {
Added test: Button menu variant brand with label

2022-03-15 14:05 UTC, nawel-aa approved these changes

2022-03-15 18:14 UTC, merged