Feature abc 479 add is joined to page header
avonni/base-components pull request #276
Opened 2022-03-10 20:38 UTC by lgilmet

Added storybook controls and implemented isJoined to add slds-page-header_joined. Works on vertical too.

2022-03-11 16:20 UTC, nawel-aa requested changes
The broken tests should be fixed, and new ones should be added for the new attribute.
And don't forget to keep Confluence up to date! 🙂

2022-03-11 16:20 UTC, nawel-aa commented on src/modules/base/pageHeader/__examples__/base/base.html
> +        is-joined={isJoined}
The base example is normally as uncustomized as possible, but you can add `is-joined` to one of the other examples (`objectHome`, for example), and change it in the stories too.

2022-03-11 16:20 UTC, nawel-aa commented on src/modules/base/pageHeader/pageHeader.html
>                                          <template if:true={hasStringTitle}>
The `if:true` can be placed directly on the new spans, we don't need the `<template>` tags anymore.

2022-03-11 20:52 UTC, lgilmet commented on src/modules/base/pageHeader/__examples__/base/base.html
> +        is-joined={isJoined}
I just forgot it there after trying to make storybook work.

2022-03-15 14:03 UTC, nawel-aa approved these changes

2022-03-15 14:26 UTC, lgilmet commented
Doc
- [ ] https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1766457432/Page+Header

2022-03-15 18:13 UTC, merged