[feat][wip] (ABC-514): Add responsive stretch class
avonni/base-components pull request #279
Opened 2022-03-15 17:11 UTC by lgilmet

Make vertical buttons full width (.slds-button_stretch) with a boolean.

2022-03-16 20:10 UTC, lgilmet commented on src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
> +                '[data-element-id="span-checkbox-container"]'
The tests were failing and this fixed them.

2022-03-16 20:11 UTC, lgilmet commented on src/modules/base/inputChoiceSet/inputChoiceSet.css
> +.avonni-input-choice-set__stretch .slds-checkbox_button__label {
Both buttons and labels need to be flex-grow = 1.

2022-03-16 20:17 UTC, lgilmet commented
Ready for review

2022-03-17 14:27 UTC, lgilmet commented
Behavior approved by JB. Stretch checkboxes and radio to full width and wrap around.

2022-03-17 19:03 UTC, nawel-aa requested changes
The only required change is the removal of a line in the doc file. The other comments are suggestions or answers. 😊

2022-03-17 19:03 UTC, nawel-aa commented on src/modules/base/inputChoiceSet/inputChoiceSet.js
> +        return classSet(`${this.orientation}`).add({
I know this was already there, but could you give a more specific name to the "orientation" class? It could raise problems when used in Avonni, if there's a class named "horizontal" or "vertical" at the app level.

2022-03-18 12:54 UTC, lgilmet commented on src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
> +                '[data-element-id="span-checkbox-container"]'
Ok interesting

2022-03-18 12:55 UTC, lgilmet commented on src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
> + * @property {boolean} stretch If present, vertical or horizontal button groups stretch to full width.
Right, it's already added by js doc in the attribute table. I forget things :P

2022-03-18 15:01 UTC, nawel-aa requested changes
The tests are broken, because of the class name change I made you do. 😊

2022-03-18 15:23 UTC, lgilmet commented
> The tests are broken, because of the class name change I made you do. 😊

🤦‍♂️ There!

2022-03-18 15:40 UTC, nawel-aa approved these changes
😃 🎉

2022-03-21 12:51 UTC, merged