[feat] (ABC-513): Add fallback bullet for omitted icons
avonni/base-components pull request #286
Opened 2022-03-25 19:06 UTC by lgilmet

Add isActive to item. If item has no icon it has a gray bullet. If also isActive, item has a blue bullet.

<img width="296" alt="Screen Shot 2022-03-31 at 11 19 25 AM" src="https://user-images.githubusercontent.com/36134032/161090745-994d541b-9ad8-4d40-8c00-c5c94d7a9c83.png">

https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1620082724/Activity+Timeline
https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1621819399/Activity+Timeline+Item

2022-03-31 16:38 UTC, nawel-aa requested changes
Works well. 👍 My main request is about the truncation that I know can be fixed. 😊

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
> +        expect(element.index).toBeFalsy();
We usually use `toBeFalsy()` for booleans. Here it could be `toBeUndefined()`, or maybe even `toBe(0)`, since it's supposed to be a number?

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
> +}
This is a complicated solution for a simpler problem, you can fix it by fixing your truncation problem at the same time. 🙂

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
> +                            <span class="slds-trucate">
Why adding a `<span>` around the `<a>`? If anything, you could make it even simpler by adding the `if:true` directly on the <a>.
Also, I trust that you can figure out how to make `slds-truncate` work. 😊 A hint is that one of the main things it does, is adding a `max-width` of 100%. But a max-width depends on the parent also having some sort of width...

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +    get hasNoIcon() {
You don't need this getter, you can do it directly in your HTML.

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +        this._index = value;
There are four reasons that come to my mind, for which we'd want to use a get/set instead of just having a `@api nameOfProperty`:
- There's a default value that you want to use if the given one is empty or invalid.
- You need to normalize the value.
- You need to do something else every time a new value is passed (for example, call a method).
- You will need to update the property yourself, so you need a private property to follow the [no api reassignment](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-api-reassignments.md) rule.

You can decide with this info if your index should be adapted to fit in one of these categories, or if you should just have an `@api index` at the top of your file. 😊

2022-03-31 16:38 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +        const icon = this.template.querySelector('.slds-timeline__icon');
I know the old code was wrong too, but this query selector should be changed to use a `data-element-id` attribute.

2022-03-31 18:06 UTC, lgilmet commented on src/modules/base/activityTimeline/activityTimeline.html
>              <template for:each={sortedItems} for:item="item">
For those with a section, the first of every section becomes first, but have to mark only the very first item :(
<img width="318" alt="Screen Shot 2022-03-30 at 10 51 43 AM" src="https://user-images.githubusercontent.com/36134032/161121062-3fedc9fb-b850-4181-b2a3-1a426c8206f0.png">

2022-03-31 18:19 UTC, lgilmet commented on src/modules/base/activityTimeline/__examples__/progressIndicator/progressIndicator.html
> +        collapsible="true"
true true true

2022-03-31 18:22 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
> +        expect(element.index).toBeFalsy();
toBeUndefined, there is no default.

2022-03-31 18:30 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.html
>              <template for:each={sortedItems} for:item="item">
Silly me! 😃
You could still have a `groupIndex` attribute and an `index` attributes that should both be equal to 0, but your way is cleaner! 👌 You do have to reset your `_iterator` property every time the items are updated, though.

2022-03-31 20:38 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
> +                            <span class="slds-trucate">
slds-truncate doesnt wanna work in the item header. it's all flex 😢.

2022-03-31 20:55 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +        this._index = value;
touché

2022-03-31 21:32 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
> +                            <span class="slds-trucate">
made it work 😌

2022-04-01 14:45 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
> +                            <span class="slds-trucate">
This
```
<!-- this div.slds-has-flexi-truncate does the magic -->
<div class="slds-has-flexi-truncate">
    <h3 class="slds-truncate">
        {title}
    </h3>
</div>
```

2022-04-01 14:48 UTC, lgilmet commented on src/modules/base/activityTimeline/activityTimeline.html
>              <template for:each={sortedItems} for:item="item">
😤

2022-04-01 15:09 UTC, nawel-aa approved these changes
🎉

2022-04-05 12:17 UTC, nawel-aa reviewed
Works well! 👍 I only have a small suggestion about the tests. :)

2022-04-05 12:17 UTC, nawel-aa commented on src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
> -            expect(items[0].index).toBe(0);
I think this test can be removed. But you should add a line for `isActive`, in the test named "Activity Timeline: items".

2022-04-05 12:55 UTC, lgilmet commented on src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
> -            expect(items[0].index).toBe(0);
great!

2022-04-05 12:59 UTC, nawel-aa approved these changes

2022-04-05 18:05 UTC, merged