ABC-512 Add label to calendar dates
avonni/base-components pull request #287
Opened 2022-03-28 19:35 UTC by lgilmet

I tried to explore prior commits in the last branch and ended up with a messy mix of old and new code.

2022-03-28 19:38 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +                    dayClass = 'avonni-calendar__disabled-cell slds-day';
.slds-day was missing. All days must have it.

2022-03-28 20:07 UTC, lgilmet commented on src/modules/base/calendar/__tests__/calendar.test.js
> +    // this test does nothing
I have to redesign this test. The use of .slds-day is wrong.

2022-03-29 13:55 UTC, nawel-aa requested changes
**Other comment:**
In the input date range, if you are on the end input and you select a past date, it should fill the start date.

2022-03-29 13:55 UTC, nawel-aa commented on src/modules/base/calendar/__docs__/calendar.stories.js
> -    disabledDates: '05/09/2021'
The changes made to the stories could be reflected in the docs examples, for more consistency when the users look at the [prod storybook](https://storybook.avonnicomponents.com/).

2022-03-29 13:55 UTC, nawel-aa commented on src/modules/base/calendar/calendar.css
> +td > .slds-day,
I'm afraid using the `td `and `tr` tags directly is a risk, because my understanding is that in Avonni, the style sheets are shared among all components. So if a user has its own calendar using the SLDS classes, our style sheet will apply. But you can just add a default class to all `td` tags and use it instead of `td`, it should avoid any conflict. :)

2022-03-29 13:55 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +            this._dateLabels = [];
Use normalizeArray() instead.

2022-03-29 15:00 UTC, lgilmet commented on src/modules/base/calendar/calendar.css
> +td > .slds-day,
I replaced all td, tr and th from css with classes.

2022-03-29 15:07 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +                    let iconOnlyLabel =
Right!!!

2022-03-29 17:35 UTC, lgilmet commented on src/modules/base/chip/__docs__/chip.jsdoc.js
> + * @type dimension
And here too: https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1424064563/Chip

2022-03-30 19:36 UTC, jbverger approved these changes

2022-03-30 19:36 UTC, merged