Feature abc 522 add date range accessibility
avonni/base-components pull request #301
Opened 2022-04-20 17:22 UTC by lgilmet

2022-04-28 20:34 UTC, nawel-aa requested changes
I didn't look at the date range, because they are things to fix with the calendar first:
- We don't want to trap the focus in the calendar, unless it is inside the popover of the date picker.
- When we select a date in the calendar with the keyboard or the mouse, the focus should stay on this date.

Bonus: if you're looking to refactor, I think we could use a second class `CalendarDate`, instead of having the huge `generateViewData` method.

2022-04-28 20:34 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +                fullDate = time;
If you're going to set `fullDate` to `time` anyway, you don't need to have a variable. You can just set it in the object you're pushing into `weekData`.

2022-04-28 20:34 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +                    clickedDate: this._clickedDate
For more consistency, it would be better if the `clickedDate` was an ISO string, instead of a date object.
Also, don't forget to update the JSDoc comment just above, and the Confluence documentation.

2022-04-28 20:34 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +    handleFocusOut() {
I'm not sure why you need to implement this in the calendar. It seems like if the parent component needs it, it could do it itself around the calendar, since the advantage of `focusin` and `focusout` is that they bubble up. Also, `closingMethod` really only applies to the case where the calendar is inside a popover, but it's a component in itself that doesn't "close".

2022-04-28 20:34 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +     * direction is number of days (+ : after, - : before)
The method's arguments should be documented through the [correct syntax](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Allowed-block-tags-for-methods) (`@param {number} Description of the argument`). Don't hesitate to add the [JSDoc snippets](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#VSCode-snippet-configuration) to your VSCode, or make your own.

2022-04-28 20:34 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +                let currentDate = this.date.getTime();
All of the next variables could be constants. Always set your variables to a `const` first, and **then** update them to a `let` if you realize you need to edit them.

2022-04-29 17:42 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +    @api
done

2022-04-29 18:54 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +                let currentDate = this.date.getTime();
My reflex is always `let` :(

2022-05-04 20:12 UTC, nawel-aa requested changes
**Calendar:** 
- When selecting a date with the keyboard, the focus should stay on the selected date.
- When tabbing in the calendar, only one date should be focusable. The date should be one of these, in this order:
  -  The last date the user has set focus on.
  - Today's date.
  - The first available date of the month.
  - The 1st of the month, if all dates are disabled.

**Input Date Range:**
- When selecting a date with the keyboard, the calendar should close and the focus be set on the calendar button icon. It should not jump to the next input. With the mouse, it should keep the current behaviour.
- Could you add to the description of the value property, that it is read-only?

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +            }, 10);
Why using a timeout to set a property? It will trigger a second rerender.

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +    checkInputDatesValidity() {
There already are public methods to check the validty of the inputs, you should use them.

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
>      _valid = true;
There are already methods and a getter (this.validity), you shouldn't need another property.

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +        this.checkInputDatesValidity();
There is a method to check the validity. If the parent component wants to blur and validate, they can call `reportValidity()` after `blur()`

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +    onFocusOut() {
This is an event handler, it should start with "handle" and should not be decorated with `@api`, since it is not supposed to be called from the parent component.

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +        }, 1);
Why have a `setTimeout` of one and not 0?

2022-05-04 20:12 UTC, nawel-aa commented on src/modules/base/inputDateRange/inputDateRange.js
> +    clickDateInput(event) {
By convention, this event handler should start with "handle" to be easily identified as one.

2022-05-11 13:37 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +                this._nextFocusDate = this.min;
Removed

2022-05-11 13:38 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +
Removed

2022-05-11 13:39 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +    }
Removed

2022-05-11 18:05 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +            }, 10);
Refactored

2022-05-11 19:44 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +        }, 1);
Refactored

2022-05-12 17:44 UTC, closed without merging

2022-05-12 17:44 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +        this.checkInputDatesValidity();
done

2022-05-12 17:45 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
>      _valid = true;
done

2022-05-12 17:57 UTC, lgilmet commented on src/modules/base/inputDateRange/inputDateRange.js
> +    // UTILITIES //
Got it I think