[fix] (ABC-606) Color Gadrient drag and event propagation
avonni/base-components pull request #330
Opened 2022-05-11 18:51 UTC by AchilleStH

### Fixes
**Color Gradient**
- The color picker indicator is now draggable
- The hue slider was set to the left when the color selected was in the corner of the gradient

2022-05-12 14:56 UTC, nawel-aa requested changes
It works, but there is a console error when the input is disabled and we try to drag the indicator, probably because you moved the mousedown handler's position. 🙂

2022-05-12 14:56 UTC, nawel-aa commented on src/modules/base/colorGradient/colorGradient.js
> +            : 'slds-color-picker__custom-range';
This works well, but we usually use `classSet()` for this type of application. It makes it easier to identify which classes are always present and which depend on specific conditions.

2022-05-13 15:18 UTC, nawel-aa commented on src/modules/base/colorGradient/colorGradient.js
> +import { classSet } from '../utils/classSet';
Instead of using local imports, we use the namespace `c/` to be able to change the file structure without impacting the components. So in this case, it would be `import { classSet } from 'c/utils'`

2022-05-16 20:53 UTC, nawel-aa approved these changes

2022-05-17 13:08 UTC, jbverger approved these changes

2022-05-17 13:08 UTC, merged