[feat](ABC-549): Activity timeline: Add max-visible-items and show more/show less button to display specific number of items
avonni/base-components pull request #332
Opened 2022-05-12 13:54 UTC by GenevievePMD

### Features
Activity Timeline
- Added an option to set a maximum of visible items to display and show more / show less button.

2022-05-12 15:54 UTC, nawel-aa requested changes
It works, but there are small styling/convention issues.

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
> +        element.items = ITEM;
Since the content of the items doesn't matter for your tests, you can use the `testItems` variable that was already created.

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
> +        element.buttonIconName = 'utility:up';
I think you meant `element.buttonShowLessIconName`, maybe? But I don't think you need to set it at all.

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +     * Label of the button to display only the max-visible-items number of items.
This description is a bit confusing. I like the one you added to [Confluence](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1620082724/Activity+Timeline) better. 😊

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +     * Position of the show button’s icon. Valid values include left and right.
*show **less**

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +     * Position of the show button’s icon. Valid values include left and right.
*show **more**

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +     * Variant of the button that appears when the number of item exceeds the max-visible-items number.
*number of item**s**

2022-05-12 15:54 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +        if (this._isConnected) this.initActivityTimeline();
Two things:
- By convention, we usually start the methods that are used as event handlers with "handle". So here it could be "handleToggleShowMoreButton".
- You don't need the `if (this._isConnected)`, because once the user can interact with the component, it means that it is rendered. So in the [lifecycle](https://lwc.dev/guide/lifecycle), we have passed the `connectedCallback`.

2022-05-12 19:52 UTC, nawel-aa approved these changes
Everything works! 🎉

2022-05-12 19:52 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +            this._maxVisibleItems = DEFAULT_MAX_VISIBLE_ITEMS;
Do you still need this, or did you forget to remove it? 🙂

2022-05-18 17:21 UTC, jbverger requested changes

2022-05-18 17:21 UTC, jbverger commented on src/modules/base/activityTimeline/activityTimeline.js
> +        if (value && value > 0) this._maxVisibleItems = value;
You need to add "{" and "}".
Should be 
`if (value && value > 0) {
      this._maxVisibleItems = value;
}`

2022-05-19 15:09 UTC, jbverger approved these changes

2022-05-19 15:13 UTC, jbverger approved these changes

2022-05-19 15:14 UTC, merged