[feat](ABC-532) : ActivityTimeline : Add controls to change size of icons
avonni/base-components pull request #336
Opened 2022-05-12 17:39 UTC by GenevievePMD

### Features
ActivityTimeline
- Added iconSize and itemIconSize to customize size of icons

2022-05-16 12:41 UTC, nawel-aa requested changes
Nice catch to think of scaling the action icons! :)
Aside from my comments in the code, the main problem is that without icons (last story), the line is not aligned when we change the item icon size.

2022-05-16 12:41 UTC, nawel-aa commented on src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
> +                '.slds-media__figure > lightning-icon'
You should add a `data-element-id` attribute to the icon, so your tests don't depend on classes.

2022-05-16 12:41 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +     * The size of the title's icon. Valid values are x-small, small, medium and large.
You're missing the `xx-small` in the accepted values, for both documentation descriptions. :)

2022-05-16 12:41 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
> +.avonni-activity-timeline-item-timeline-action-icon-xx-small {
Ideally, you should use [our version of the BEM convention](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587118095/CSS#Class-naming) to name your classes, which I think in this case would be: `avonni-primitive-activity-timeline-item__action-icon_xx-small`.
It makes very long names, and I know it hasn't been used well in many components (including this one), but if you create new classes, may as well name them the way it's supposed to be. 😊

2022-05-16 12:41 UTC, nawel-aa commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +    isActionIcon() {
Since there is no parameter to the method and it is returning a value, this should be a `get isActionIcon()`, not a method. And you should make sure the `iconName` is a string before using `split()` on it, because `iconName` doesn't have a get/set where we transform an invalid value into a string.

2022-05-16 21:00 UTC, nawel-aa approved these changes

2022-05-18 17:23 UTC, jbverger approved these changes

2022-05-18 17:23 UTC, merged