[fix] (ABC- 593) Timer - broken count-down and much more
avonni/base-components pull request #340
Opened 2022-05-13 18:31 UTC by Felino203

### Features
Timer
- Timer works with milliseconds.
- 2 new display formats: "mm:ss.ms" & "ss.ms"

### Fixes
Timer
- Value attribute is now given in milliseconds instead of seconds
- Pause now works.
- Reset method now works.
- Repeat attribute now works.
- Refactored formatting to be flexible. Can now easily add more display formats.

2022-05-16 14:45 UTC, nawel-aa reviewed
Works well overall! 👍
- For the stories that don't have autoplay, it would be nice to add buttons to start/stop/reset the timer. To do so, you have to create a storybook wrapper in the `storybookWrapper` folder, and change the component imported in `timer > __examples__`. Checkout the other components that use a wrapper for examples (and let me know if it's unclear).
- The value change from seconds to milliseconds makes a lot of sense, but it's a breaking change, so I would check with @jbverger that's okay, if you haven't already.
- Very small detail, but could you reorder the getters and the public methods in alphabetical order?

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/__tests__/timer.test.js
> +    it('Timer: type = count-up', () => {
These two tests are not really checking if the type works. What we really want when we set the type to "count-up", is that once the timer starts, the label of the lightning-button gets a bigger value over time. Here, you're testing the `start()` method and the `timerstop` event more than the type attribute. :)

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/__tests__/timer.test.js
> +    it('Timer: repeat = false', () => {
Here you could also check if the button's label is up to date, since that's the end result the users will actually see.

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/timer.js
> +            }, 10);
You can probably set the timeout to 0, or even better, use `requestAnimationFrame(() => {})`, since what you want is to wait for the component rerender.

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/timer.js
> +        return this._timerValue;
Is there a specific reason to rename `_value` to `_timerValue`? It's clearer to keep the same name for the private and public properties.

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/timer.js
> +        let hours = Math.floor(this._timerValue / 60 / 60 / 1000);
Don't forget to use `const` instead of `let`, when you can. :)

2022-05-16 14:45 UTC, nawel-aa commented on src/modules/base/timer/timer.js
>      createInterval() {
This method can probably be refactored a little to be more readable. Instead of having a lot of if/else, you could have a constant of which you change the value depending on the current state, and/or a few boolean constants with a clear name. For example:
```
const isCountUp = this.type === 'count-up';
const hasEndedCountUp = isCountUp && this._timerValue >= this._startTime + this.duration;
const hasEndedCountDown = !isCountUp && (this._timerValue <= maxTime || Math.abs(this._timerValue) >= MAX_TIMER_VALUE);

let state;
if (this.play && hasEndedCountUp) {
    state = 'RESET_COUNT_UP';
} else if (this.play && isCountUp) {
   state = 'COUNT_UP';
} else if () { ... }

switch (state) { ... }
```

2022-05-26 13:05 UTC, nawel-aa requested changes
Sorry I forgot to mention it before, but the examples in `__examples__` should be updated to include the new storybook wrapper. The goal is that the examples on our website match the examples in storybook. 🙂

PS: I edited your pull request comment, because we have a new "breaking change" category in [our release notes](https://www.avonnicomponents.com/release-notes).

2022-05-26 14:59 UTC, Felino203 commented
Don't know if there is a way for me the test the __examples__ I added and modified. Either way, I think they should work. :)

2022-05-27 12:37 UTC, nawel-aa reviewed
The storybook buttons don't work anymore (see my comment), but the component looks good to me! 👍

2022-05-27 12:37 UTC, nawel-aa commented on src/modules/base/storybookWrappers/timer/timerButtons.js
> -        return this.template.querySelector('c-timer');
I think you may have done this change by mistake? In the documentation examples, we do want to use `avonni-timer` instead of `c-timer`: in the website, we use the base components package, and the `c` namespace is not exposed in it.
But in the storybook wrapper, you don't need to use `avonni`, you can use `c`. In any case, if you make the change in the JS file, you should rename `c-timer` to `avonni-timer` in the HTML file too, because right now the buttons don't work anymore. 🙂

2022-05-31 01:39 UTC, merged