Fix abc 566 carousel three items per panel
avonni/base-components pull request #341
Opened 2022-05-13 20:27 UTC by ivanivanov-github

### Fixes
**Carousel**
- Displays correctly multiple items per panel
- Converts bare and border action variants to menu variant on small and large mobile devices

2022-05-16 15:28 UTC, nawel-aa reviewed
The bug is fixed and the button menu looks good!

On top of my other comments, I noticed two things that were already there, but could be nice to fix:
- The click on an action should stop the propagation of the click event, to prevent the wrapping `<a>` tag from taking over.
- The HTML of the primitive carousel item could be split into two: one with the <a> tag, and the other without. To do so, you can use render() (see [the doc](https://lwc.dev/guide/html_templates#render-multiple-templates) or search the code base for examples).

2022-05-16 15:28 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
> +    it('Primitive Carousel Item: actions variant border with large and small mobile device', () => {
The `Object.defineProperty` is clever. 😊 But these tests will always pass, because the `lightning-button-menu` is always present in the DOM, it's just hidden by the CSS. If you want to add a test for it, you could check if the right classes are applied to both the button menu, and the regular button/button-icon.

2022-05-16 15:28 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/primitiveCarouselItem.css
> +.avonni-carousel__button-icon-top {
I'm not sure why you removed the surrounding margin and padding. It's good to have some space between the actions.

2022-05-30 13:15 UTC, nawel-aa requested changes
A few small changes needed.
If my comments on the tests aren't clear, don't hesitate to let me know. :)

2022-05-30 13:15 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
> +            const tag = element.shadowRoot.querySelectorAll(
This test pass only because you used `querySelectorAll` instead of `querySelector`, so you'll always have an empty node list, even if there is no element. 🙂 Normally, by default, the `noTag` template would be called. And if you add an href, the `tag` template would be called.

2022-05-30 13:15 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/noTag.html
>          if:false={href}
The `if:false` can be removed, because this template won't be used if there is an `href`.

2022-05-30 13:15 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/noTag.html
> +                            onclick={handleActionClick}
If you add the `onclick` to the button menu, the `actionclick` event will be dispatched every time we click on the menu, with the wrong action name. Instead you can remove the `onclick` handlers on the menu and the items, and add an `onselect` one (see the [Salesforce doc](https://developer.salesforce.com/docs/component-library/bundle/lightning-button-menu/documentation) for a description of the event).

2022-05-30 13:15 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/tag.html
> +        if:true={href}
You can remove the `if:true` since this template will never be called if there is no `href`.

2022-06-08 13:04 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js
> +    handleMenuSelect(event) {
As discussed the other day, what we want is either to use the [`select` event dispatched by the `lightning-button-menu`](https://developer.salesforce.com/docs/component-library/bundle/lightning-button-menu/documentation) (ideal), or to use the click event on each menu item (slightly less efficient).
In either case, the `actionclick` event should be dispatched only once: when we click on an action.

2022-06-08 13:05 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/noTag.html
> +                            onclick={handleActionClick}
Don't forget to make the change for all the button menus. 🙂

2022-06-08 13:09 UTC, nawel-aa requested changes
- I forgot to mention it, but you may have noticed yourself: if you create several HTML templates, the CSS files that you want to attach to them need to have the same names. To prevent duplicating CSS, you can have three files: `tag.css`, `noTag.css` and `shared.css`. In `shared.css` you keep the CSS that is shared by the two templates. In the two others you add an `@import` rule (see the `primitiveSchedulerEventOccurrence` component for an example).
- Don't hesitate to click on the "resolve" button of my comments when you fix the issue. I won't be mad and it can help you see what is left to do. 😊

2022-06-10 17:36 UTC, nawel-aa requested changes
You still need two CSS files, with the exact same name than the HTML file (`tag.css` and `noTag.css`). Otherwise, the CSS file is not linked to the HTML. The `shared.css` file you created needs to be imported in both files through an [`@import rule`](https://developer.mozilla.org/fr/docs/Web/CSS/@import). You can check out the `primitiveSchedulerEventOccurrence` component for an example.

2022-06-10 17:36 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/shared.css
> +    padding: 1px;
My old comment from a few reviews ago still stands: why do you remove the margin/padding? And if you need to do so, I think you don't need these classes, you can change `computedLightningButtonIconActionClass` in the Javascript file, to not apply the `slds-m-...` classes. 🤔

2022-06-10 17:36 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/shared.css
> +.avonni-carousel__image {
`avonni-carousel__image` doesn't seem to be applied to anything. This declaration should be removed.

2022-06-10 17:36 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/shared.css
> +    padding: 4px;
To make sure we always use the same kind of values for padding/margin, we try to only use the [Lightning Design System classes](https://www.lightningdesignsystem.com/utilities/padding/). You should add the one you want to `computedActionsContainerClass` in your Javascript.

2022-06-10 17:36 UTC, nawel-aa commented on src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
> +            expect(result).toBeFalsy();
The way to test if an event has been prevented, is to check its [`defaultPrevented`](https://developer.mozilla.org/fr/docs/Web/API/Event/defaultPrevented) value. So instead of using `action.click()`, you could create a `CustomEvent`, make `action` dispatch it, and then check if `yourCustomEvent.defaultPrevented` is `true`. 🙂

2022-06-16 19:13 UTC, ivanivanov-github commented on src/modules/base/primitiveCarouselItem/noTag.html
> +                    <template if:false={isMenuVariant}>
Yes, it simplified the code quite a bit 😅.

2022-06-16 19:22 UTC, ivanivanov-github commented on src/modules/base/primitiveCarouselItem/shared.css
> +    padding: 1px;
I don't need to do so. I've removed the unnecessary classes.

2022-06-20 13:12 UTC, nawel-aa approved these changes
Everything works, congrats! 👍

2022-06-20 13:20 UTC, jbverger approved these changes

2022-06-20 13:20 UTC, merged