[Feature] (ABC-599): Created new component - chip container
avonni/base-components pull request #350
Opened 2022-05-17 20:42 UTC by Felino203

### Features
Chip Container
- Display a list of chips from list of items (see doc)
- Possibility of displaying either an avatar or icon as media (left or right)
- Possibility of changing media size
- Collapsible and expandable

2022-05-20 14:51 UTC, nawel-aa requested changes
- You should use a storybook wrapper to add a `max-width` around your component, so the difference between the collapsed and non-collapsed container is obvious in your stories. You can check the pill container's storybook wrapper for an example.
- You should add [an example per story](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Documenting-examples) in the `__examples__` folder.
- The avatars and items objects that you documented as tables in Confluence [should also be documented](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Documenting-objects) in a `.jsdoc.js` file, in the `__doc__` folder.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +    calculateWrappedNodes() {
It's just a suggestion, but I think it would be cleaner to add a `hidden` attribute to your primitive chip and let it handle the class change.
- You would have to change your HTML so the chip **is** the list item (in that case use [aria roles](https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/listbox_role) instead of the `<ul>` and `<li>` tags).
- You would update the item objects when the `is-expanded` / `is-collapsible` attributes are changed, instead of doing the calculation at every rerender. Ideally, to not change the value given by the user, you should create a `computedItems` to which you would add the key you need (see the `list` for an example).

Another (and simpler) way to go, is to not change anything to the chips, and simply rely on the fixed height and `overflow: hidden` of the parent container. That's what the lazy pill container is doing. 😊

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +        ).style.height = `${tallest.clientHeight}px`;
This will raise an error if no items were set, since `tallest` will be undefined.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.css
> +.avonni-chip-container__wrapper_is-collapsed {
You should remove unused selectors.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.css
> +.slds-listbox_selection-group {
If you need to overwrite an slds class, you should either not use it, or you should apply a second custom class to make sure your CSS selector is specific to this component. Otherwise, once in Avonni, the CSS won't be split into components, and this rule may apply to other components.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.css
> +.avonni-chip-container__wrapper_small {
I don't think these classes are used.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/__tests__/chipContainer.test.js
> +    /* ----- ATTRIBUTES ----- */
We usually try to write the attributes' tests in alphabetical order (`alternative-text`, then `is-collapsible`, etc.). It's mostly important for bigger test files, but always a good habit to have. 😊

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/__tests__/chipContainer.test.js
> +            expect(itemsContainer.childElementCount).toBe(3);
You can also test if your items did receive all of their properties. You can check out the pill container items' test for an example.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +
We need the [@class JSDoc](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Allowed-block-tags-for-classes) comment for this component to appear in our doc, with an `@public` tag.

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/primitiveChip/primitiveChip.js
> +            const tempAvatar = JSON.parse(JSON.stringify(value));
You can use `normalizeObject(value)` to make sure your `JSON.parse(JSON.stringify())` doesn't raise an error if the user gave the wrong value format. I also personally prefer using the `deepCopy` utility, I find that the purpose is clearer, but that's your choice. 😊

2022-05-20 14:51 UTC, nawel-aa commented on src/modules/base/primitiveChip/__tests__/primitiveChip.test.js
> +    /* ----- ATTRIBUTES ----- */
You miss a test for `iconName`.

2022-05-24 15:44 UTC, Felino203 commented on src/modules/base/chipContainer/chipContainer.js
> +    calculateWrappedNodes() {
Since I was asked to remove the option to resize chips, all chips should be of similar enough size to use the "lazy" method. The reason I had to hide them, was because some large chips where visible when wrapped even because the wrapper also scaled with their size. I will remove the hidden class now that it is not needed.

2022-05-24 15:49 UTC, Felino203 commented on src/modules/base/chipContainer/chipContainer.js
> +    calculateWrappedNodes() {
Nevermind... there is too much of a height difference between an chip with an avatar, and one with only a label. I will have to implement the longer method.

2022-05-25 14:09 UTC, nawel-aa requested changes
- You still miss [an example per story](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Documenting-examples) in the __examples__ folder. You need to create one component per storybook example, with the exact same settings as used in the story. These components will be copied and displayed in [our website](https://www.avonnicomponents.com/) when we do the package release.
- The tests are broken because of the last changes.

2022-05-25 14:09 UTC, nawel-aa commented on src/modules/base/primitiveChip/__tests__/primitiveChip.test.js
> +            // cannot test the value of the html element that displays the icon
Hmmm... Yes you can. If you retrieve the left icon element and use `expect(icon.iconName).toBe('utility:user')`, it should work.

2022-05-25 14:09 UTC, nawel-aa commented on src/modules/base/primitiveChip/primitiveChip.css
> +.avonni-primitive-chip__hidden {
It would make more sense to use `display: none` instead of `visibility`, since you don't want the element to take any room. And you can even use the class [`slds-hide`](https://www.lightningdesignsystem.com/utilities/visibility/#Hide-Show) instead of using a custom CSS file. 🙂

2022-05-25 15:41 UTC, Felino203 commented on src/modules/base/chipContainer/chipContainer.js
> +            this.calculateWrappedNodes();
It is needed here because on initialization, the resize observer callback is not called. So we have to manually call it once on render.

2022-05-27 12:39 UTC, nawel-aa approved these changes
🎉

2022-06-23 02:18 UTC, jbverger approved these changes

2022-06-23 14:55 UTC, nawel-aa requested changes
It still works, and the consistent height looks much better!
See also my comment on Jira.

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/__docs__/chipContainer.jsdoc.js
> + * @typedef {object} ChipContainerItems
Don't forget to update this doc now that `mediaPosition` doesn't exist anymore (see the changes I made in Confluence). 🙂

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/__docs__/chipContainer.stories.js
> +    isExpanded: false
Not a big deal, but it may save you time on other components: since these are the default values of `alternativeText`, `isCollapsible` and `isExpanded`, you don't need to add them to the story. 😊

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/__examples__/base/base.js
> +            prefixIconName: 'utility:down', // not shown since there is an avatar
Don't forget to remove this comment when you make the change asked for in Jira. 🙂

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/__examples__/collapsed/collapsed.js
> +            prefixIconName: 'utility:down', // not shown since there is an avatar
Don't forget to remove this comment when you make the change asked for in Jira. 😊

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +            'avonni-chip-container__list-box_height': true,
If the class is always present, you can chain it inside the `classSet()` separated by a space. So in your case: `classSet('slds-listbox_selection-group avonni-chip-container__list-box_height')`.

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +        return isCollapsible && !this.computedIsExpanded;
I'm not sure of it because I've twisted my mind trying to understand this complicated boolean chain. 😅 But it feels like you just need to return `this.isCollapsible && !this.isExpanded`?

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/chipContainer/chipContainer.js
> +    set hasMedia(value) {
Since you only set `hasMedia` with a `true` value, I think for more clarity, you could just add this block of code to `checkForMedia()`? That way you don't even need a `_hasMedia` property.

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/primitiveChip/primitiveChip.js
> +        if (value) {
What if there used to be an avatar, but now I want to remove it? 😊 It's unlikely in this case because it's a primitive you have control over, but as a general rule, you should allow to remove a value already set.

2022-06-23 14:55 UTC, nawel-aa commented on src/modules/base/primitiveChip/primitiveChip.js
> +        this._showIcon = true;
What if the `prefixIconName` was set to `undefined` or `null`? `this._showIcon` would still be set to `true`. You can probably check if there is a prefix or suffix icon in the `get showIcon()` directly. 🙂

2022-06-27 13:07 UTC, nawel-aa reviewed
Only little refactoring comments. Everything works well. 🙂

2022-06-27 17:34 UTC, Felino203 commented on src/modules/base/chip/chip.html
> +                    slds-grid slds-grid--vertical slds-grid--align-center
They seem to exist since they have an effect on the component style. I downloaded a vscode LWC snippets extension, and these were part of the LWC library. I guess LWC changed their naming conventions at one point and these are either new classes, or old ones. I changed them to the new conventions, but I cant make it work with slds-grid_vertical-align-center when there is no media (I want justify center on vertical flex, not align center on horizontal flex).

2022-06-28 14:34 UTC, nawel-aa commented on src/modules/base/chip/chip.html
> +                    slds-grid slds-grid--vertical slds-grid--align-center
Oh, I see, they do seem to have changed the dashes for underscores. I see you found the new syntax for the classes you actually needed. Nice! 🙂

2022-06-28 14:35 UTC, nawel-aa approved these changes
Looks good to go! 🚀

2022-06-30 01:56 UTC, jbverger approved these changes

2022-06-30 01:56 UTC, merged