[feat](ABC-531) Activity timeline: Added option to specify datetime format
avonni/base-components pull request #352
Opened 2022-05-18 17:53 UTC by GenevievePMD

### Features
Activity Timeline
- Added option to specify a datetime format

2022-06-08 13:35 UTC, nawel-aa requested changes
Only one tiny thing! 😊
I think the date format should not be a way to hide the date. If the date format is invalid, the default format should be used, the date should not disappear.

2022-06-22 13:23 UTC, nawel-aa requested changes
I'm sorry I hadn't read the Jira task instructions last time, where it specifically say to hide the date when the format is empty. 😅 I still think it's clearer this way, but @jbverger's opinion may differ.

2022-06-22 13:23 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +        return this._closed;
I suppose it was supposed to be `this._hideItemDate`, instead of `this._closed`?

2022-06-22 13:23 UTC, nawel-aa commented on src/modules/base/activityTimeline/activityTimeline.js
> +            this._itemDateFormat = '';
What if `hideDateFormat` is set to `false` later? How do we get the format back? 😊  It would be safer to either:
- Pass a `computedDateFormat` (or other name of your choice) as the primitives `date-format`. It would return an empty string if `hideItemFormat` is true, or the `itemDateFormat` otherwise.
- Pass `hideItemDate` to the primitives, and use it in their `formattedDate`.

2022-06-22 13:23 UTC, nawel-aa commented on src/modules/base/activityTimeline/__examples__/withoutIcons/withoutIcons.html
> +        hide-item-date="true"
Since it would be `true` whatever the string was (it would still be `true` if you had written `hide-item-date="false"`), we just write the name of the attribute (`hide-item-date`), without a value.

2022-06-23 14:59 UTC, nawel-aa approved these changes
Looks perfect to me! 👍

2022-06-27 12:29 UTC, jbverger approved these changes

2022-06-27 12:29 UTC, merged