New Card component
avonni/base-components pull request #357
Opened 2022-05-20 20:52 UTC by lgilmet

### Features
**Name of the Component**
- First feature
- Second feature

### Fixes
**Name of the Component**
- First feature
- Second feature

2022-06-13 14:27 UTC, nawel-aa requested changes
It works well. 👍 
On top of the other comments, maybe you could add a div with a max-width to the storybook wrapper and the examples? I'm afraid otherwise the examples will be too big in our doc website.

2022-06-13 14:27 UTC, nawel-aa commented on src/modules/base/card/card.css
> +    flex-direction: row-reverse;
[`slds-grid_reverse`](https://www.lightningdesignsystem.com/utilities/grid/#Right-to-Left)

2022-06-13 14:27 UTC, nawel-aa commented on src/modules/base/card/card.css
> +    flex-direction: column-reverse;
[`slds-grid_vertical-reverse`](https://www.lightningdesignsystem.com/utilities/grid/#Bottom-to-Top)

2022-06-13 14:27 UTC, nawel-aa commented on src/modules/base/card/card.css
> +.avonni-card__media-background .avonni-card__media-container,
Everything except the `media-left`? If so, you can use `.avonni-card__body-container:not(.avonni-card__media-left) .avonni-card__media-container`.

2022-06-13 14:27 UTC, nawel-aa commented on src/modules/base/card/card.js
> +    _mediaPosition = 'top';
It should be set to `MEDIA_POSITIONS.default`

2022-06-13 17:46 UTC, lgilmet commented on src/modules/base/card/__docs__/card.jsdoc.js
> + * @default '0 2px 2px 0 rgba(0, 0, 0, 0.1)'
Ok it just looked weird with the first string being highlighted and the rest looking like a comment :) but you are right.

2022-06-13 17:48 UTC, lgilmet commented on src/modules/base/card/__docs__/card.jsdoc.js
> + * @name --avonni-card-header-font-size
👍

2022-06-13 17:49 UTC, lgilmet commented on src/modules/base/card/__docs__/card.jsdoc.js
> + * @name --avonni-card-text-color
👍

2022-06-13 17:49 UTC, lgilmet commented on src/modules/base/card/__docs__/card.jsdoc.js
> + * @namespace slots
👍

2022-06-13 18:26 UTC, lgilmet commented on src/modules/base/card/card.js
> +    get title() {
🤦‍♂️

2022-06-13 18:27 UTC, lgilmet commented on src/modules/base/card/card.js
> +    get mediaSrc() {
🤦‍♂️

2022-06-13 18:28 UTC, lgilmet commented on src/modules/base/card/card.js
> +     * Valid values are "top", "center", "left", "right", "bottom", "background", and "overlay". Defaults to "top".
👍

2022-06-13 18:34 UTC, lgilmet commented on src/modules/base/card/__docs__/card.stories.js
> +    }
👍

2022-06-13 18:35 UTC, lgilmet commented on src/modules/base/card/__examples__/mediaBackground/mediaBackground.html
> +        media-position="top"
You understood the example name correctly.

2022-06-13 19:31 UTC, lgilmet commented on src/modules/base/card/card.css
> +    display: flex;
I can use slds-grid and slds-scrollable_none!

2022-06-13 19:54 UTC, lgilmet commented on src/modules/base/card/card.css
> +.avonni-card__media-background .avonni-card__media-container,
Cool!

2022-06-13 20:31 UTC, lgilmet commented on src/modules/base/card/__examples__/mediaLeft/mediaLeft.html
> +        style="--avonni-card-left-media-width: 140px"
Using a smaller image solves this issue.

2022-06-13 20:31 UTC, lgilmet commented on src/modules/base/card/card.css
> +.avonni-card__body-container {
👍

2022-06-13 20:56 UTC, lgilmet commented on src/modules/base/card/card.css
> +    flex: 1 1 auto;
On image left and right the slds-col (flex: 1 1 auto) is overridden by slds-has-flexi-truncate (flex: 1 1 0%). But it is overridden by our own class.

2022-06-14 15:27 UTC, lgilmet commented on src/modules/base/card/card.js
> +        this.showMedia = !!this.mediaSrc || this.showMediaSlot;
Fixed

2022-06-14 15:34 UTC, lgilmet commented on src/modules/base/card/card.css
> +    flex-direction: column-reverse;
👍

2022-06-14 15:35 UTC, lgilmet commented on src/modules/base/card/card.css
> +    margin-right: 0.75rem;
👍

2022-06-14 15:37 UTC, lgilmet commented on src/modules/base/card/card.css
> +    display: flex;
👍

2022-06-14 17:30 UTC, lgilmet commented on src/modules/base/card/card.css
> +    flex-direction: row-reverse;
The slds-grid_reverse does not respect the flex shrink and grow.

2022-06-15 13:54 UTC, nawel-aa requested changes

2022-06-15 13:54 UTC, nawel-aa commented on src/modules/base/calendar/calendar.js
> +                event.stopPropagation();
As discussed, you can remove all the `event.stopPropagation()`.

2022-06-15 13:54 UTC, nawel-aa commented on src/modules/base/card/__tests__/card.test.js
> +        window.requestAnimationFrame.mockRestore();
Mocking the `requestAnimationFrame` and using fake timers is not really a problem, but it's only necessary if you actually use `requestAnimationFrame` or timeouts. 🙂

2022-06-15 13:54 UTC, nawel-aa commented on src/modules/base/card/card.js
> +            'slot[data-element-id="avonni-card-default-slot"], slot[data-element-id="avonni-card-center-default-slot"]'
Ha! I didn't know you could chain the selectors like that! 😃

2022-06-15 13:54 UTC, nawel-aa commented on src/modules/base/card/card.js
> +     * Card body classes ... slds-grid_vertical
I'm assuming this is a copy-paste mistake, and not a very suspenseful and mysterious description. 😄

2022-06-15 15:01 UTC, lgilmet commented on src/modules/base/card/card.js
> +import { normalizeString } from '../utilsPrivate/normalize';
👍

2022-06-15 15:02 UTC, lgilmet commented on src/modules/base/card/card.js
> +     * Card body classes ... slds-grid_vertical
🤦‍♂️

2022-06-15 15:02 UTC, lgilmet commented on src/modules/base/card/card.js
> +            'slot[data-element-id="avonni-card-default-slot"], slot[data-element-id="avonni-card-center-default-slot"]'
This one is useful :P

2022-06-15 15:04 UTC, lgilmet commented on src/modules/base/card/card.js
> +        this.showTitleSlot =
Of course thanks

2022-06-15 15:15 UTC, lgilmet commented on src/modules/base/card/__docs__/card.stories.js
> +    // title: 'Card Title',
I gotta start doing that, reviewing the changes in isolation. 🤦‍♂️

2022-06-15 15:15 UTC, lgilmet commented on src/modules/base/card/card.html
> +                        <template if:true={showTitleSlot}>
Good catch

2022-06-15 15:21 UTC, lgilmet commented on src/modules/base/card/__docs__/card.stories.js
> -                defaultValue: { summary: 'top' }
Ah I see it now. I wondered where that "table" was.

2022-06-15 15:24 UTC, lgilmet commented on src/modules/base/card/__tests__/card.test.js
> +        window.requestAnimationFrame.mockRestore();
I tried solving a problem and forgot it there.

2022-06-15 15:37 UTC, lgilmet commented on src/modules/base/card/card.css
> +    display: flex;
👍

2022-06-15 17:43 UTC, lgilmet commented on src/modules/base/calendar/calendar.js
> +                event.stopPropagation();
👍

2022-06-16 13:57 UTC, nawel-aa approved these changes
🎉

2022-07-11 12:14 UTC, merged