[feat] (ABC-617): Kanban component
avonni/base-components pull request #358
Opened 2022-05-24 13:39 UTC by AchilleStH

### Features
**Kanban**
- New kanban component created

2022-06-09 17:42 UTC, nawel-aa requested changes
Really nice job! 👌  
I didn't review the tests, because you'll have enough changes to make that they may change. I also have two more comments:
- Since you have an extra "Types and Type Attributes" table in [the Confluence doc](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/366444586/Kanban#Types-and-Type-Attributes), you need to add a `.md` file to reflect it in [our documentation website](https://www.avonnicomponents.com/). You can check out `scheduler/__docs__/scheduler.md` or `datatable/__docs__/datatable.md `for examples.
- Only a left click should trigger the drag and drop behaviour.

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +            if (this.variant === 'base') field.style.height = 'fit-content';
Per [the new rule](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019795/Javascript#Avoid-using-one-liners) requested by JB, your ifs should be wrapped in curly braces. 🙂

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +                field.style.height = `${container.offsetHeight}px`;
I'm not sure why you need to set the height of the fields, so I may be wrong. 😊 But if it is for the visual boxes to take only the height of their content, you can just add a `<div>` inside the one that is in flex, and apply the style to it, instead of applying it to the "column" `<div>`.

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +        const SUMMARY_UPDATE_SPEED = 300;
Nice idea to make `SUMMARY_UPDATE_SPEED` a constant! You should declare it at the top of the file, so it would be an actual global constant, and to make it easier to find it if we want to change the speed.

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +    capFieldHeight() {
Same thing as above: I haven't dived into it, so correct me if I'm wrong. But it feels like if the parent element has a `max-height` of 100%, and all of its children too, you shouldn't need to compute a height limit in your Javascript, everything should be handled with CSS. 🤔

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +        this._kanbanPos.top = currentTarget.getBoundingClientRect().top;
Can't you use `currentTarget.getBoundingClientRect()` for all the sides (bottom and right included)?

2022-06-09 17:42 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +                cancelable: true
If the event is cancelable, it should actually cancel the change when `preventDefault()` is called on it by the parent component.
I don't know if it is what we want (maybe discuss it with @jbverger), but if it is, you should implement it. 😊 You can see an example of implementation in the `dispatchClick()` of the `primitiveTreeItem`.

2022-07-26 20:27 UTC, nawel-aa requested changes
See also my comment on Jira, and let me know if anything isn't clear! 🙂

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +    ) !important;
If you can avoid using `!important`, it's better. I'm assuming an SLDS class is bothering you. If so, make sure you can't recreate it instead of using it.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +    display: flex;
Instead of using `display: flex` everywhere, you can usually use `slds-grid`. Checkout [the LDS utilities](https://www.lightningdesignsystem.com/utilities/grid/), almost all the flex properties have a corresponding class.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +.avonni-kanban__tiles_container {
Can you use the [scrollable class](https://www.lightningdesignsystem.com/utilities/scrollable/) utilities instead?

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +    display: none;
Can you use `slds-hide`, instead?

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +    /* position: sticky;
Don't forget to remove comments.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.css
> +    display: none;
Can you use `slds-hide`, instead?

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/__docs__/kanban.jsdoc.js
> + * @default 1.25rem
That's not the default value used in the CSS for the font-size.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/__docs__/kanban.jsdoc.js
> + * @default 14.5em
That's not the default value used for the min-width in the CSS.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/__tests__/kanban.test.js
> +    it('Kanban : Default attributes', () => {
`hideHeader` and `subGroupFieldName` should appear in the default attributes.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/__tests__/kanban.test.js
> +    it('Kanban : tile drag and drop', () => {
You should test if the `change` event has been dispatched properly when we drag the tile.

2022-07-26 20:27 UTC, nawel-aa commented on src/modules/base/kanban/__tests__/kanban.test.js
> +describe('Kanban', () => {
I think you can test the `actionclick` event too.

2022-08-02 14:51 UTC, AchilleStH commented on src/modules/base/kanban/__tests__/kanban.test.js
> +    it('Kanban : tile drag and drop', () => {
So, i fixed pretty much everything but the tests... I might need your help here 😵‍💫.

The problem seems to be that the tests can't compute the groups ( the `_computedGroups` array is always empty ) in the function `updateTiles()` called in the `connectedCallback()`...

This causes the `for:each` loops to iterate over an empty array in the HTML thus not rendering the groups, subgroups, tiles etc... causing most of the querySelectors to return `null` ( only happens in tests, even when all the attributes are set ).

I tried to fix it yesterday without success, have you ever encountered something similar ?

2022-08-02 15:07 UTC, nawel-aa commented on src/modules/base/kanban/__tests__/kanban.test.js
> +    it('Kanban : tile drag and drop', () => {
I think your problem comes from the fact that you create the `computedGroups` only in the `connectedCallback()`. This works in Storybook, because the component is recreated from scratch every time we change a property value. 

In the tests (which is closer to a real case situation), the component is appended to the DOM in the `beforeEach()`, which is when the `connectedCallback()` is called. Afterwards, when you update a property, it will only go through its `set()` and the `renderedCallback()`, never through the `connectedCallback()`. The way to fix your problem, is to set a `_connected` property to `true` in the `connectedCallback()`. In each property `set()` that is used in `updateTiles()` (`groupValues`, `records`, etc.), if `_connected` is `true`, call `updateTiles()`.

Does it make sense? 🙂

2022-08-02 15:33 UTC, AchilleStH commented on src/modules/base/kanban/__tests__/kanban.test.js
> +    it('Kanban : tile drag and drop', () => {
Works perfectly 🙌

2022-08-03 14:27 UTC, nawel-aa requested changes
Nice refactor! 👍 Your code is easier to read and the structure is clearer.
On top of the small comments here, I noticed a few bugs left that you can see in Jira. Also, in `kanban.js`, `animateSummary`, `capContainerWidth`, `capFieldHeight` and `setContainerDimensions` should not execute if `isLoading` is `true`, since they rely on elements that won't be in the DOM.

2022-08-03 14:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +                    droppedTo:
- Instead of `droppedTo`, `groupValue` would be more consistent with what we have in other components, and with `tileId`.
- Don't forget to update the JSDoc comment above, and Confluence.

2022-08-03 14:27 UTC, nawel-aa commented on src/modules/base/kanban/__tests__/kanban.test.js
> +            expect(handler).toHaveBeenCalled();
You should also test that the events `detail` contain the write info, and that it bubbles/composed/cancel or not. You can see the `actionclick` test in `avatar.test.js`, for an example. This comment is also true for your `actionclick` test. 🙂

2022-08-03 14:27 UTC, nawel-aa commented on src/modules/base/kanban/kanban.html
>      <lightning-spinner if:true={isLoading}></lightning-spinner>
I missed it in my last review, but you should add an `alternative-text` to the spinners in both templates. We usually use `"Loading..."`. 🙂

2022-08-03 14:27 UTC, nawel-aa commented on src/modules/base/kanban/kanbanSubGroups.css
> +.avonni-kanban__field_disabled_column_drag .avonni-kanban__summarize_wrapper {
The declarations that are repeated between `kanban.css` and `kanbanSubGroups.css` should be added to a `shared.css` file, and then imported in both files with an `@import './shared.css'`. You can checkout `primitiveSchedulerEventOccurrence` for an example.

2022-08-08 13:17 UTC, nawel-aa requested changes
Almost there. 🙂
- There is still a bug with the drag and drop (see Jira).
- `key-field="id"` needs to be added to all the examples HTML files.

2022-08-08 13:17 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +     * @public
Good catch on adding `@required` to `groupFieldName`. You should also add it for `keyField`.

2022-08-08 13:17 UTC, nawel-aa commented on src/modules/base/kanban/kanban.js
> +        const keyField = event.currentTarget.dataset.keyField || '';
The default value for empty `targetKeyField` or `groupValue` should be `undefined`, not an empty string.

2022-08-08 13:17 UTC, nawel-aa commented on src/modules/base/kanban/kanban.html
> +                        <div if:true={group.headerActions}>
Since `group.headerActions` will always be an array, it should be `if:true={group.headerActions.length}` (don't forget to update the second template too).

2022-08-09 14:24 UTC, nawel-aa approved these changes
Everything looks good to me! Congrats! 🥳

2022-08-30 19:40 UTC, nawel-aa requested changes
See my comment on Jira, there is an error with the scrolling interval.

2022-09-01 14:48 UTC, nawel-aa requested changes
The tests are broken. 🙂

2022-09-06 18:18 UTC, nawel-aa approved these changes
I think we're all good! 👌

2023-05-15 15:15 UTC, jbverger approved these changes

2023-05-15 15:15 UTC, merged