Feature abc 610 create bar code component
avonni/base-components pull request #359
Opened 2022-05-24 20:14 UTC by ivanivanov-github

### Features
**Barcode**
- New barcode component

2022-05-30 14:30 UTC, nawel-aa requested changes
The component works, but of course I have comments. 😊 
You should also remove the empty `mocked-version-of-bwip.js` file.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +import { LIBRARY_ENCODING_VALUE, BARCODE_LIBRARY } from 'c/utilsPrivate';
You can merge the two `c/utilsPrivate` imports.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +     * @type {number}
I think the value type is string, not number?

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        this._size = value;
You should call `setCanvasWidth()` in `set size()` if the first render already happened, in case the size is changed after the first render (which can happen in a real life example).

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    @api
I don't think this getter needs to be public, you can remove the `@api` tag.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    @api
I have identified [4 cases where you need to have a get/set](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019795/Javascript#Use-of-getter%2Fsetter-for-public-fields) for a public property.
I think `background` and other of your properties do not fit any of these case, so you can declare them at the top of the file, the same way you did for `value`. 🙂

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +     * PRIVATE PROPERTIES
The code below corresponds to private methods, not properties.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    getBarcodeLibrary() {
Since they don't take any argument, always return a value, and don't update the value of another property, the three `getSomething()` methods could be converted into actual private `get something()`.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    initBarcode() {
Since `initBarcode()` is only calling `setCanvasWidth()`, I think you can remove it and just call `setCanvasWidth()` instead.

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        let element = this.template.querySelector(
This `let` could be a `const`. 🙂

2022-05-30 14:30 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    @api
I don't think this method needs to be accessible by the parent component of the barcode. You can remove the `@api`.

2022-06-09 14:28 UTC, ivanivanov-github commented on src/modules/base/barcode/barcode.js
> +    @api
You're right, it doesn't need to be accessible. However I used it to be able to call the function in the tests. Should I leave it, or not use the function in the tests?

2022-06-10 15:21 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +    @api
If it's only for the test, you should remove it. The `@api` is supposed to decorate only methods that it would make sense to call from outside of the component. Moreover, once we deploy it to Salesforce, we will never be able to remove or rename this method. Salesforce prevents us from deleting public properties/methods, so we have to really think twice before creating one. 😅

What you need in your tests, is to allow the component to rerender after you change its properties. If you look at other tests, this is why we always add a `return Promise.resolve()` after changing the element's properties. This will trigger the rerender, which should trigger the call to your `renderBarcode()` method. 🙂

2022-06-16 15:23 UTC, ivanivanov-github commented on src/modules/base/barcode/barcode.js
> +    @api
Got it! I've made the necessary changes!

2022-08-30 10:06 UTC, closed without merging