[Feat] (ABC-654) new slider component - Slider
avonni/base-components pull request #368
Opened 2022-06-07 14:53 UTC by Felino203

### Features
Slider
- The avonni slider allows to pick a value on a range. The value attribute can be set to an array of number to allow a range style slider.
- Allows for LDS unit attributes and custom labels.
- Vertical and Horizontal styles.
- Tick marks can be displayed on the range.
- Allows for slider track and thumb customization with styling hooks (see doc).
- Value validation following LDS syntax.
- Allows for decimal steps, up to 0.001

2022-06-14 15:48 UTC, nawel-aa requested changes

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +    get privateMin() {
Same comment than above, you can just rename `_computedMin` and `_computedMax` to `computedMin` and `computedMax`.

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +    get _thumbRadius() {
The styling hook may be set on a parent component, and it will still apply to the slider. Also, the radius could be set in % or any other unit. If you want to get the width of the element, try `offsetWidth` or `getBoundingClientRect`.

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +    get _trackHeight() {
Same comment as above, use Javascript to get the height, not the CSS variables.

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +            this.template
You can probably use `this.template.activeElement` instead?

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +        this._hideTrack = this._computedValues.length > 2 || this._hideTrack;
If I understand this line correctly, once the track has been hidden, it will never be unhidden, even if the value is changed.

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +                this._computedValues[parseInt(event.target.dataset.index, 10)]
- To prevent long lines, use a variable for the index.
- It's better to use `currentTarget` when possible, in case a child element triggered the event, and not the element itself. In this case it doesn't matter because nothing will ever be in the `<input>`, but keep it in mind. 🙂 
- Don't forget to use `const` instead of `let`.

2022-06-14 15:48 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +            pin.style.left = `calc(${pinProgress}% - ${
Do you have to do the calculation in the CSS? If not, it's cleaner to to it in the Javascript, since you're already setting the CSS style here.

2022-06-14 16:20 UTC, Felino203 commented on src/modules/base/slider/slider.js
> +    setClosestOnTop(event) {
An inputs' thumb cannot be dragged unless it is on top of the other input (or else the same input will always be targeted y clicks). This calculation serves to set the thumb closest to the mouse on top, so that clicking on the input track will call the event on the closes thumb (<input type=range> thumb and track are linked and cannot be selected individually).

2022-06-15 18:54 UTC, Felino203 commented on src/modules/base/slider/slider.js
> +    get _thumbRadius() {
This method lets me get the computed style which still applies to slider. Also, it is the only method I know of that works to get a pseudo element attribute.

2022-06-15 18:56 UTC, Felino203 commented on src/modules/base/slider/slider.js
> +     * The variant changes the appearance of the slider. Accepted variants include standard and label-hidden.
I dont know... the LWC slider does not have that variant and JB did not insist on him. I should ask what he thinks of this, since an inline-label variant would be nice to have.

2022-06-17 13:50 UTC, nawel-aa requested changes
See my comment on Jira. 🙂

2022-06-27 13:42 UTC, nawel-aa requested changes

2022-06-27 13:42 UTC, nawel-aa commented on src/modules/base/slider/slider.js
> +        console.log(parentHeight);
...and don't forget to remove the console logs! 😊

2022-06-28 14:50 UTC, nawel-aa requested changes

2022-06-28 14:50 UTC, nawel-aa commented on src/modules/base/slider/__examples__/vertical/vertical.html
> +            hideMinMaxValues
The attributes must be written in kebab case, so `hide-min-max-values` instead of `hideMinMaxValues`.

2022-06-30 14:00 UTC, nawel-aa requested changes
I'm sorry I missed all the `messageWhen...`  in my previous reviews! Can you remove these ones? They don't make sense for the slider. 🙂
- `messageWhenBadInput`
- `messageWhenTypeMismatch`
- `messageWhenValueMissing`

2022-06-30 14:37 UTC, nawel-aa approved these changes
Everything's good, nice job! 👍

2022-07-06 11:11 UTC, merged