[Feature] (ABC-662) Added signature pad & more - Input Pen
avonni/base-components pull request #387
Opened 2022-06-30 18:17 UTC by Felino203

### Features
Input Pen
- Added showSignaturePad boolean property to add a signature pad visual to the canvas.
- Added a paintbrush tool, that draws smooth lines and has blurry edges.
- Added an ink tool that draws smooth lines and changes size depending on velocity.
- Added background fill option, to fill a color of choice.
- Added a download button for downloading a PNG of the current canvas.
- Added added a undo/redo functionality (with keyboard shortcut support (ctrl-z/ctrl-y)).
- Moved the clear button to the top right of the canvas and changed the icon to a reset wheel.

### Fixes
Input Pen
- Validity reporting now works as intended.

2022-07-04 13:20 UTC, nawel-aa requested changes
I only noticed small things to change, and a few interrogations you can choose to ignore if I didn't understand correctly the purpose of your code. Nice job overall, and a fun component to test! 😊

2022-07-04 13:20 UTC, nawel-aa commented on src/modules/base/inputPen/straightToolManager.js
> +        super.setupLine();
If you remove the empty methods in `toolManager.js`, don't forget to remove their calls here (see my comment in the other file).

2022-07-05 20:21 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +const DEFAULT_SIZE = 10;
2 pixels was way too small in my opinion. I think 10 is much better. Will mark as breaking change.

2022-07-05 20:23 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +        window.addEventListener('mouseup', this.onMouseUp);
this was code that was reused from the previous component... and to be honest, I had no clue what bind() did. Will fix.

2022-07-05 20:25 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +        window.addEventListener('mouseup', this.onMouseUp);
Also I think they are being put in a variable so they can be removed in disconnected callback. Is that necessary? I will remove it since I don't see it in any other component.

2022-07-05 20:42 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +        if (hexColorRegex.test(normalizedValue)) {
The value is use from the color picker change event is always hexadecimal, so I don't think it is possible to break.

2022-07-05 20:45 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +        window.addEventListener('mouseup', this.onMouseUp);
**On your first comment:** `bind` basically transfers `this` (the context) to the method (for example `handleMouseUp`). It allows you to use `this` and all the methods/properties of the component in `handleMouseUp`. 🙂 Arrow functions [have more subtleties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), but in this case, they would serve the same purpose: use the context in which they were called.

**On your second comment:** Theoretically, if they are applied to the component's elements, [LWC removes the event handlers automatically](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.events_handling) when the component is disconnected. But you need to remove the listener applied to `window`, because this one won't, and it could cause memory leaks.

2022-07-05 20:52 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +            this.initResizeObserver();
Aaaah, I see! No, you're right, between the two, it's better not to break the input! 😊

2022-07-05 21:00 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +        if (hexColorRegex.test(normalizedValue)) {
No, I'm sure it won't break, but the color could be given as an `rgb()` color or even a keyword (like `blue`). Your normalization is too strict. 🙂

2022-07-05 21:03 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +            !this.disabledButtons ||
disabledButtons does not have a getter and setter, can I add one, or is that a breaking change?

2022-07-05 21:13 UTC, Felino203 commented on src/modules/base/inputPen/inputPen.js
> +        if (hexColorRegex.test(normalizedValue)) {
oops I thought the comment was on background fill event handler... thats my bad.

2022-07-05 21:17 UTC, Felino203 commented on src/modules/base/inputPen/toolManager.js
> +    setupLine() {
No, but I think its better to keep them there in case we add a new tool (with handler) and that tool requires the same interface. I think its more clear. Since JavaScript does not have the "Interface" or "abstract class" keyword like in TypeScript, its the solution I found.

2022-07-07 13:27 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +            !this.disabledButtons ||
Yes you can, it won't be a breaking change! 🙂
Breaking changes are changing the previous behaviour of a component. So it would be a breaking change if `disabledButtons` was previously expecting a string, for example, and we were changing its value to an array. But `disabledButtons` was always supposed to receive an array per the documentation. So this is just a normalization making sure the parent component didn't send an invalid value.

2022-07-07 13:55 UTC, nawel-aa requested changes
Tiny changes on top of my two answers from the last review. 🙂

2022-07-07 13:55 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.html
> +                        <ul class="slds-button-group-list">
`<ul>` tags can only contain `<li>` tags. To make [imbricated lists](https://developer.mozilla.org/fr/docs/Web/HTML/Element/ul#liste_imbriqu%C3%A9e), you need to wrap the nested `<ul>` in a `<li>`.

2022-07-07 13:55 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +import { AvonniResizeObserver } from '../resizeObserver/resizeObserver';
The resizer should still be imported from `c/resizeObserver`.

2022-07-07 13:55 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +        this.keyDownCallback = (event) => {
I wasn't clear, but what I meant was transforming the original handle methods (`handleMouseUp`, `handleMouseMove` and `handleKeyDown`) into arrow methods (`handleMouseUp = (event) => {}`).

2022-07-12 12:55 UTC, nawel-aa requested changes
- The tests are broken because:
  1. `handleKeyDown` should be an arrow function.
  2. `disabledButtons` only accepts an array of strings, not a unique string. You can either:
      - Transform strings into an array containing a unique string in the `set disabledButtons`.
      - Change the values passed in your tests for arrays.
- I'm guessing the changes you made to the HTML in the past broke the responsiveness of the toolbar (see Jira for screenshots). I'm sorry I forgot to check before. 😊

2022-07-26 14:17 UTC, nawel-aa requested changes

2022-07-26 14:17 UTC, nawel-aa commented on src/modules/base/inputPen/inputPen.js
> +        if (event.keyCode === 89 && event.ctrlKey) {
Unfortunately, on a Mac we use `Command+Z` and `Command+Shift+Z`, not the `Control` key. So this is breaking the undo/redo shortcuts. I think the best way to do it is the one suggested on [this Stackoverflow exchange](https://stackoverflow.com/questions/65429466/best-way-to-listen-for-cmd-shift-z-and-cmd-z-using-javascript) (except the Z should be lowercase).

2022-07-26 20:48 UTC, nawel-aa approved these changes
🚀

2022-08-08 10:24 UTC, merged