[doc](ABC-686): Profile card - Changed attribute size to avatarSize
avonni/base-components pull request #389
Opened 2022-06-30 19:51 UTC by renaudaf

### Features
**Profile Card**
- Changed attribute size to avatarSize

2022-08-02 19:35 UTC, nawel-aa requested changes
You forgot to update the storybook wrappers. 🙂

2022-08-02 19:50 UTC, renaudaf commented
Done! Merci

2022-08-02 19:53 UTC, nawel-aa approved these changes
👍

2022-08-08 10:25 UTC, jbverger approved these changes

2022-08-08 10:25 UTC, merged