Feature ABC-539 Refactor list component
avonni/base-components pull request #403
Opened 2022-08-03 14:30 UTC by lgilmet

added single-line and grid variant. 
added infinite scrolling

2022-08-18 17:40 UTC, nawel-aa requested changes
- Checkout my comment in Jira on ABC-625.
- You should delete the `out847` folder.
- You need to update Confluence.
- The `@class` description should be updated in `list.js`.
- The `list.js` file content [should be reordered](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019795/Javascript#File-order).
- As a general advice: read your changes before committing! It will help prevent `console.log`, comments and random files/folders from being committed.

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        const tempHoveredIndex = parseInt(
Try to use named variable in each of your `if()`, so we know what each condition means (`moveToTop`, `moveToBottom`, or anything like that).

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            '.avonni-list__item-menu'
Query selectors should always use `data-element-id`.

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            '[data-index="' + this._initialDraggedIndex + '"]'
Per our [general Javascript rules](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019795/Javascript#General-rules), favour interpolation of `this._initialDraggedIndex` over concatenation with +.

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        scrollStep = closeToTop ? -5 : closeToBottom ? 5 : 0;
Avoid chaining ternary operators, it's very hard to read. Use an if/else for your `scrollStep`, instead.

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this._scrollStep = scrollStep;
It's a little weird to both return the `scrollStep`, and store it in a property. I would not return anything, and use `this._scrollStep` in `autoScroll()`.

2022-08-18 17:40 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            currentItemTransform =
This line is a little too long to be understood easily, and I'm pretty sure what you're trying to retrieve would be way clearer with a regex.

2022-08-18 19:45 UTC, lgilmet commented on src/modules/base/list/__docs__/list.stories.js
> +            minimum: 1,
Ah thanks!

2022-08-18 19:48 UTC, lgilmet commented on src/modules/base/list/list.js
> +     * Number of columns in the grid.
Thanks

2022-08-18 20:17 UTC, lgilmet commented on src/modules/base/list/list.js
> +    _columns;
Yes I caught that too.

2022-08-19 13:34 UTC, lgilmet commented on src/modules/base/list/list.js
> +            this.hasImages &&
This is to show the actions in the media-action slot. We chose to use only the media-action slot for the grid or single-line.

2022-08-19 14:53 UTC, lgilmet commented on src/modules/base/list/list.js
> +        let _value = cols;
Thanks that's much neater.

2022-08-19 14:56 UTC, lgilmet commented on src/modules/base/list/list.js
> +                this.renderNumber !== 0
Should not be there.

2022-08-19 15:11 UTC, lgilmet commented on src/modules/base/list/list.js
> +        setTimeout(() => {
I don't need it anymore.

2022-08-19 15:22 UTC, lgilmet commented on src/modules/base/list/list.js
> +        this._scrollStep = scrollStep;
Yes thanks, no need to return if the value is stored in this._scrollStep.

2022-08-19 15:33 UTC, lgilmet commented on src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
> +
🤦

2022-08-19 17:47 UTC, lgilmet commented on src/modules/base/list/list.js
> +            currentItemTransform =
This is more elegant!

```
const matrix = new DOMMatrixReadOnly(currentItem.style.transform)
const currentItemYTransform = matrix.f;
```

2022-08-22 13:02 UTC, lgilmet commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @name --avonni-list-item-image-width
Done, with size at the end: --avonni-list-item-image-height-small.

2022-08-22 15:50 UTC, lgilmet commented on src/modules/base/list/list.html
> +                                <div>
🤔

2022-08-22 17:08 UTC, lgilmet commented on src/modules/base/list/list.js
> +        if (this.renderNumber++ === 1) {
Makes sense!

2022-08-22 17:14 UTC, lgilmet commented on src/modules/base/list/list.js
> +        let calculatedColumns = this._columns;
I reformatted the whole section.

2022-08-22 18:01 UTC, lgilmet commented on src/modules/base/list/list.js
> +     * Image attributes: cropFit, position and size.
Added, to be checked.

2022-08-23 15:28 UTC, lgilmet commented on src/modules/base/list/list.js
>              Object.keys(...this.computedItems).includes('imageSrc')
Solved

2022-08-23 15:38 UTC, lgilmet commented on src/modules/base/list/list.js
> +            this.hasImages &&
I dropped the use of the card's media-action slot.

2022-08-23 15:38 UTC, lgilmet commented on src/modules/base/list/list.js
> +        let calculatedColumns = this._columns;
Re-reformatted

2022-08-24 15:43 UTC, lgilmet commented on src/modules/base/list/__tests__/list.test.js
> +// Number of columns displayed. It depends on the screen size.
Done

2022-08-25 15:42 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.stories.js
> +            minimum: 1,
Still not it, checkout the "Annotation" table in the doc, for examples. As I said, it needs to be in the `control` object. You don't have to use the validation (it's not even a good one: it only works if you use the up/down arrows), but if you do, do it well. 🙂

2022-08-25 16:00 UTC, nawel-aa commented on src/modules/base/list/__tests__/list.test.js
>          expect(element.actions).toMatchObject([]);
Nice of you to not point out that I made a typo in `element.largerContainerCols.` 😄

2022-08-25 17:23 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        if (this.variant === 'single-line') {
You could add a check for `enableInfiniteLoading` here too. I know you check again in `handleLoadMore()`, but it would avoid going the whole `handleScroll()` method every time the component render, when there is no infinite loading. 🙂

2022-08-25 17:23 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        // To check if the bottom is reached without scrolling.
After taking more time to check, I think I finally get why you need to use `requestAnimationFrame`. The card has slots that take room by default, that are removed after the first render. So my guess is you can't put `handleScroll()` directly in the `renderedCallback()`, because you need to wait for the cards to rerender, not only the list.
If I'm right, maybe add this to the comment? The comment right now is good, but it doesn't explain why you use `requestAnimationFrame`, which is the weird part of the call. 😊

2022-08-25 17:23 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        setTimeout(() => {
After taking more time to check, I think I finally get why you need to use `requestAnimationFrame`. The card has slots that take room by default, that are removed after the first render. So my guess is you can't put `handleScroll()` directly in the `renderedCallback()`, because you need to wait for the cards to rerender, not only the list.
If I'm right, maybe add this to the comment? The comment right now is good, but it doesn't explain why you use `requestAnimationFrame`, which is the weird part of the call. 😊

2022-08-25 17:35 UTC, nawel-aa commented on src/modules/base/list/list.js
> +     * @type {number}
You're missing the `@default 1`

2022-08-25 17:35 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @name --avonni-list-item-image-width
Hmmm... I think maybe it would make more sense to add styling hooks per variant, instead of height/width? So we would have:
- `--avonni-list-grid-item-image-size-large`
- `--avonni-list-grid-item-image-size-medium`
- `--avonni-list-grid-item-image-size-small`
- `--avonni-list-list-item-image-size-large`
- etc.
Because the height/width makes it look like whatever the variant, they can be updated. That way someone can for example change the size of all the lists in single-line, over a whole website. What do you think? 🤔

2022-08-25 17:36 UTC, nawel-aa commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @name --avonni-list-item-image-width
Arguably, the `list-list` is a little weird. 😅

2022-08-25 17:39 UTC, nawel-aa commented on src/modules/base/list/list.js
> +     * Image attributes: cropFit, position and size.
Looks good! 🙂 We usually don't put quotes around the values and properties ('small', 'object-fit', etc.), but it's a detail.

2022-08-25 17:45 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            currentItemTransform =
It was! 👌 I'm sorry Jest got angry. Don't forget to remove the comments, if you're not getting back to it.

2022-08-25 18:28 UTC, nawel-aa requested changes

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.css
> +.avonni-list__grid-display {
Can you use `slds-wrap` instead?

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.css
> +.avonni-list__lower-spinner-spacer {
Don't forget to remove the spinner spacer classes when you'll be done with it.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.css
> +    width: 100%;
You can either chain the classes (`.avonni-list__image-slot, .avonni-list...`), or even use one class for all of these elements. And you can use `slds-is-relative` for the positioning.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.html
> +            <!-- check when is loading, and scroll to see it if already all the way down -->
Don't forget to remove the comment when you'll be done with the spacer.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            // window.requestAnimationFrame(() => this.showLoading());
Don't forget to remove this comment.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    showLoading() {
To prevent the scroll from happening on the first appearance of the scroll bar, you should also check if we are at the top of the screen. If we are, it means we never scrolled, and we shouldn't scroll down.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this.computedItems.forEach((item, index) => {
The variant should also be added to the computed items here, in case you update the variant first, and then the items.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    get showSpinnerSpacer() {
Don't forget to remove everything related to the spinner spacer.

2022-08-25 18:28 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    }
`actions` should always be an array, so I think it is safe to just check for this.actions.length, without the first verification

2022-08-25 19:08 UTC, lgilmet commented on src/modules/base/list/list.js
> +    get showSpinnerSpacer() {
I didn't want to delete it until I had a good replacement 😅. 
It's dead now.

2022-08-25 19:28 UTC, lgilmet commented on src/modules/base/card/card.html
> +                        style="overflow: hiddden"
🤦‍♂️

2022-08-26 13:12 UTC, lgilmet commented on src/modules/base/list/list.html
> +            <li class={computedSpinnerClass} if:true={showSpinnerSpacer}>
You're right

2022-08-26 13:50 UTC, lgilmet commented on src/modules/base/list/__docs__/list.jsdoc.js
> - * @type string
🤦‍♂️

2022-08-26 15:33 UTC, lgilmet commented on src/modules/base/card/card.html
> +                        style="overflow: hiddden"
🤦‍♂️

2022-08-30 18:09 UTC, nawel-aa requested changes

2022-08-30 18:09 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    }
I missed it last time, but it's a little confusing that there is a `hasActions` and a `_hasActions`. I think you can remove the old `_hasActions` and keep your `hasActions` everywhere.

2022-08-30 18:09 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this.computedItems.forEach((item, index) => {
I missed it last time, but instead of copying `this.items` in `this.computedItems`, and then replacing each element by an `Item` object, you can directly have a `this.computedItems = this._items.map(...)`. It's a little weird to change the value of the current variable, while in a `variable.forEach()`. 🙂

2022-08-30 18:11 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this.computedItems.forEach((item, index) => {
I missed it last time, but instead of copying `this.items` in `this.computedItems`, and then replacing each element by an `Item` object, you can directly have a `this.computedItems = this._items.map(...)`. It's a little weird to change the value of the current variable, while in a `variable.forEach()`. 🙂

2022-08-30 18:12 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    }
I missed it last time, but it's a little confusing to have `_hasActions` and `hasActions`. I think you can remove the old `_hasActions` and only use your `hasActions`.

2022-08-31 13:05 UTC, lgilmet commented on src/modules/base/list/list.js
> +    _imageAttributes = {};
I was about to ask. thanks!

2022-09-02 13:18 UTC, nawel-aa requested changes
- Only two very small changes. 🙂
- It's from an old pull request, but could you fix the lack of `itemclick` on click on the item description? The problem comes from the fact that we use a formatted text for the description, but we ignore any click coming from a lightning component in `handleItemClick()`.

2022-09-02 20:27 UTC, lgilmet commented on src/modules/base/list/list.js
> +            this.showLoading();
Fixed thanks!

2022-09-06 18:31 UTC, nawel-aa requested changes

2022-09-06 18:31 UTC, nawel-aa commented on src/modules/base/list/list.html
> +                                                onclick={handleItemClick}
You don't need this `onclick` and `data-index`, you already made the needed change in `handleItemClick()`. Right now, the `itemclick` event is dispatched twice.

2022-09-06 19:01 UTC, lgilmet commented on src/modules/base/list/list.html
> +                                                onclick={handleItemClick}
Also fixed test

2022-09-06 19:05 UTC, nawel-aa approved these changes
I think it's all good! 👍

2022-09-08 14:31 UTC, nawel-aa approved these changes
All good for me! 👍

2022-09-08 20:16 UTC, merged