Feature abc 610 create barcode component
avonni/base-components pull request #431
Opened 2022-09-01 19:44 UTC by lgilmet

Refactor barcode component

2022-09-08 14:27 UTC, nawel-aa requested changes

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/__tests__/barcode.test.js
> +describe('Barcode', () => {
These tests will always pass, because they're setting a value, and then checking that the value has been set. 😊
I get that the component rely heavily on a library, so you can't test the end result. But you should check if the library is called with the right parameters each time. Something like so:

```
const handler = jest.fn();
bwipjs.toCanvas = handler;
expect(handler).toHaveBeenCalledWith('whateverarguments');
```

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +import { normalizeString } from '../utilsPrivate/normalize';
`utilsPrivate` needs to be imported from the `c` namespace.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +const TEXT_X_ALIGN = ['left', 'center', 'right', 'justify'];
To follow our convention, instead of having an array of valid values, and a default value written directly in the property, your constants should use an object with two keys: valid and default.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        this._checksum = normalizeBoolean(value);
All the properties that are used in `barcodeParameters()` should call `renderBarcode()` if the component is already connected. Their change only won't trigger a rerender, because they are not used in the DOM.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        if (numValue != null) {
- Try not using loose equality (use `!==` instead of `!=`).
- I think you should check if it is `NaN`, not if it is `null`. 🤔  And if it is invalid (null, undefined, a string, whatever), you should reset the value to an empty value, instead of keeping the old value.

(same comment for the width)

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +     * The position of the displayed value. Accepted values are top-left, top-center, top-right, top-justify, center-left, center-center, center-right, center-justify, bottom-left, bottom-center, bot
You don't need to say "Defaults to..." in the properties description, because that's what the `@default` is for. It's only for secondary objects that you have to add it at the end, because we don't have an `@default`.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +     * @type {text}
`text` is not a valid type, it should be `string`

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        if (this._textAlignment) {
There will always be a `textAlignment`, since there is a normalize.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +            this.textXAlign = normalizeString(outputAlignment[1], TEXT_X_ALIGN);
This is not the accepted format for `normalizeString`. The second argument should be an object. You can check how `normalizeString` works in the utils.

2022-09-08 14:27 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +        return `${
- Try not to make too big computations in an interpolation. It would be easier to read if you used two variables.
- What if the width and height are `undefined`, instead of `null`? Why not just check if they are present? I don't think we want a width/height of 0 anyway.
- This get() and the next one got lost in the methods section.

2022-09-08 15:52 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +        return `${
As we discussed, != null is also equal to != undefined :)

2022-09-08 15:56 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +        if (numValue != null) {
Yes, that was not intended.

2022-09-08 16:01 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +            this.textXAlign = normalizeString(outputAlignment[1], TEXT_X_ALIGN);
🤦

2022-09-09 13:33 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +        this._checksum = normalizeBoolean(value);
It was bugging when I called renderBarcode in the prop setters, so I call it only after the initial render.

2022-09-27 14:08 UTC, nawel-aa requested changes
Nice tests! 🙂
There's just a problem with the error that never goes away once it's here. And a suggestion about default values.

2022-09-27 17:13 UTC, lgilmet commented on src/modules/base/barcode/barcode.html
> +    <div if:true={validCode} class="slds-text-align_center">
I need to start testing props from the inside of the components instead of using Storybook.

2022-09-27 17:30 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +     * @default 100%
I need to change an empty string to undefined because !isNaN('') = true, because '' is a number lol
 ```
       value = value !== '' ? value : undefined;
        this._height = !isNaN(value) ? `${value}px` : value;
```

2022-09-27 19:25 UTC, nawel-aa requested changes

2022-09-27 19:25 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +     * @default 100%
- Good catch, my example was wrong, I missed the empty values cases! 🤦‍♀️  It's the same problem with `null`, and since we don't want a width of 0, you can probably use `value && !isNaN(value)`?
- My example was wrong twice, because if the value is invalid, we want to set the width back to 100% (you're doing it for `''` here, but not for `undefined` and `null`). 🙂
- You shouldn't change the value of a variable you didn't create (here `value`), it could cause a problem upstream.

2022-09-27 19:25 UTC, nawel-aa commented on src/modules/base/barcode/barcode.js
> +import { classSet } from '../utils/classSet';
A little autocompleted bad import here.

2022-09-27 19:49 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +import { classSet } from '../utils/classSet';
Thanks

2022-09-27 20:53 UTC, lgilmet commented on src/modules/base/barcode/barcode.js
> +     * @default 100%
So I made it so that undefined, null and '' are normalized to '' for height (because passing undefined to style.maxHeight does not change the height) 
and '100%' for width.

2022-09-28 12:34 UTC, nawel-aa approved these changes
Everything works well! 👍

2022-10-07 18:11 UTC, jbverger approved these changes

2022-10-07 18:11 UTC, merged