Feature abc 699 add items per panel to carousel
avonni/base-components pull request #435
Opened 2022-09-08 14:26 UTC by lgilmet

Feature: 
- Add responsive number of items per panel.

2022-09-12 13:50 UTC, nawel-aa requested changes

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/__docs__/data.js
> -        imageAssistiveText: 'Appy',
Appy is the name of [Salesforce mascot](https://appexchange.salesforce.com/appxContentListingDetail?listingId=a0N3A00000EcsHZUAZ), so this was the right assistive text. 🙂 No need to change it in all examples either.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/__tests__/carousel.test.js
> +            expect(element.smallItemsPerPanel).toBe(3)
These tests will always pass! You set a property and then check if it has been set.

Since the number of items depends on the carousel container `offsetWidth`, you can try to mock it. Here is an example of a test in the builder repo, where I mocked the `scrollHeight` of a `<ul>`, for help:
```
const list = element.shadowRoot.querySelector(
    '[data-element-id="ul-listbox"]'
);
jest.spyOn(list, 'scrollHeight', 'get').mockImplementation(
    () => 500
);
```

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +        this.initCarousel();
You need the component to have rendered for `initCarousel()` to be called.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +        this._smallItemsPerPanel = Number(
I know that's what was used for `itemsPerPanel`, but it's a weird way to check if a number is valid. Moreover, if the number is invalid, the property will be set to 0, which is itself invalid.

You can just `parseInt()` it, and check if it is greater than 10 or lesser than 1. If so, set it to `undefined`. And since it's a check you have to make in all the `set somethingItemsPerPanel()`, you can make a method out of it.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +        this.carouselIsResponsive = true;
What if `undefined` or an invalid value was just given? `carouselIsResponsive` should not be set to `true` by default. A getter would probably be more appropriate, since the value depends on several properties.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +     * Number of items to be displayed at a time in the carousel. Maximum of 10 items per panel.
...when the component is 1024px wide or more?

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +        if (!this.resizeObserver) {
If there was a resize observer and it is now useless, you should disconnect it. You should also disconnect it in the `disconnectedCallback()`, to make sure there is no memory leak. See pill container for an example.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/carousel.js
> +        }
I don't think you need this check, since the if/elseif/else below should work anyway if there is no specification for the other sizes.

2022-09-12 13:50 UTC, nawel-aa commented on src/modules/base/carousel/__examples__/responsiveItemsPerPanel/withoutPanelNavigationWithFiveItemsPerPanel.html
> +<template>
The name of this file and the JS file should be updated.

2022-09-26 19:39 UTC, lgilmet commented on src/modules/base/carousel/carousel.js
> +        this.carouselIsResponsive = true;
The property carouselIsResponsive was not useful enough to remain.

2022-09-26 19:42 UTC, lgilmet commented on src/modules/base/carousel/carousel.js
> +        this._smallItemsPerPanel = Number(
I now check in normalizeItemsPerPanel. I use it for all but default items per panel because that's the only one with a default.

2022-09-26 19:44 UTC, lgilmet commented on src/modules/base/carousel/carousel.js
> +        }
I realized that too.

2022-09-27 19:23 UTC, lgilmet commented on src/modules/base/carousel/carousel.js
> +        this.initCarousel();
Better this way? 
if (this._connected) {

2022-09-27 20:43 UTC, lgilmet commented on src/modules/base/carousel/__examples__/responsiveItemsPerPanel/withoutPanelNavigationWithFiveItemsPerPanel.html
> +<template>
I axed this example.

2022-09-27 21:11 UTC, lgilmet commented on src/modules/base/carousel/__tests__/carousel.test.js
> +            expect(element.smallItemsPerPanel).toBe(3)
It does not trigger the resizeObserver so I added small, medium and large items per panel to the untested properties.

2022-09-28 13:06 UTC, nawel-aa approved these changes
All seems good! 👌

2022-09-28 20:06 UTC, jbverger approved these changes

2022-09-28 20:06 UTC, merged