Feature abc 539 list add image position remove grid
avonni/base-components pull request #437
Opened 2022-09-12 13:12 UTC by lgilmet

Add image size and dimensions. 
Add image position left, top, right, bottom, background, overlay.
Add item spacing prop.
Remove grid.

2022-09-19 14:34 UTC, nawel-aa requested changes
- `actionclick` doesn't return the name of the action with the media-actions. Which lead me to think that maybe you should add tests for it too? 😇 

A little side note, because I see that you do it a lot:
- When you're **using** a public property, not **setting** its value, use its public name. For example, if you want to get the image width, use `this.imageAttributes.width`, not `this._imageAttributes.width`. Right now, it doesn't make a difference, because we have as a good practice to always return the private property in the `get publicProperty()`. But theoretically, we could do some computation in the `get()`, that you would skip by using the private property. It's also clearer to read, because if you use `this._imageAttributes`, I am assuming there is no public equivalent. 🙂

Little changes in the doc examples:
- I would change the "Single line with infinite loading" example to place the image at the bottom. Otherwise, on a small screen, the text is squished too much.
- I would reduce the number of columns in the "Columns with infinite loading" example, so we actually see the loading. Otherwise they are almost all loaded once.

2022-09-19 14:34 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this.setItemProperties();
- You should call `setItemProperties()` only if the component is not connected yet. Otherwise on the first connection, it will be called twice for no reason.
- You should call `setItemProperties()` in the `set` of every properties used in it. Otherwise, if a property is updated after connection, it will not update the `computedItems`.

2022-09-19 14:34 UTC, nawel-aa commented on src/modules/base/list/list.js
> +        this._dragging = false;
These lines are a duplicate from the lines above.

2022-09-19 14:34 UTC, nawel-aa commented on src/modules/base/list/list.js
> +                this._keyboardDragged = true;
These lines are duplicated.

2022-09-19 14:34 UTC, nawel-aa commented on src/modules/base/list/list.js
> +            event.target.tagName !== 'LIGHTNING-FORMATTED-RICH-TEXT' &&
This line is a duplicate.

2022-09-19 14:57 UTC, lgilmet commented on src/modules/base/list/list.js
> +                this._keyboardDragged = true;
I had a bunch of duplicates to remove after my merge. There were more than I thought 🤦‍♂️

2022-09-19 14:58 UTC, lgilmet commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @default 0px
Ahhh makes sense.

2022-09-19 20:13 UTC, lgilmet commented on src/modules/base/card/card.css
> +.avonni-card__body-container {
👍

2022-09-19 20:16 UTC, lgilmet commented on src/modules/base/list/__docs__/list.jsdoc.js
>   * @property {string} size The size of the images in the base, grid or single-line variants. In the base variant, the size controls the width of the image. On the grid and single-line variants, the s
👍

2022-09-19 20:16 UTC, lgilmet commented on src/modules/base/list/__docs__/list.jsdoc.js
> + * @typedef {Object} ListMediaAction
👍

2022-09-19 20:29 UTC, lgilmet commented on src/modules/base/list/list.css
> +a {
I totally forgot the style variables are global. Yeah repeating makes sense here.

2022-09-19 20:32 UTC, lgilmet commented on src/modules/base/list/list.js
> +        // HAS ERRORS
And you would be right!

2022-09-19 20:33 UTC, lgilmet commented on src/modules/base/list/list.js
> +     * @deprecated
🤦‍♂️ arhhhh

2022-09-20 13:49 UTC, lgilmet commented on src/modules/base/list/item.js
> +                'avonni-list__item-text-color-white':
Cool yeah I'll use ..._inverse for all white on dark text.

2022-09-20 19:42 UTC, lgilmet commented on src/modules/base/list/item.js
> +                'avonni-list__item-text-color-white':
I used `.avonni-list__item-text-color_inverse`.

2022-09-20 19:42 UTC, lgilmet commented on src/modules/base/list/list.css
> +    --default-text-color: white;
Refactored

2022-09-21 17:37 UTC, nawel-aa requested changes
Almost there! I only have a few styling hook defaults and doc comments. 🙂

2022-09-21 17:37 UTC, nawel-aa commented on src/modules/base/list/list.css
>  a.avonni-list__item-info-link {
I hadn't noticed, but you miss the `:active` pseudo-class here.

2022-09-21 17:37 UTC, nawel-aa commented on src/modules/base/list/list.css
> +    --slds-c-icon-color-foreground: var(--avonni-list-item-icon-color-foreground-inverse, white);
I think we don't want a fallback value for `--avonni-list-item-icon-color-background-inverse` (`transparent`) and `--avonni-list-item-icon-color-foreground-inverse` (`white`). 🤔  If you use a standard icon, you may want the original colours.

Same comment for the non-inverse class, where you can also remove the fallback value to `--avonni-list-item-icon-color-foreground-default`.

2022-09-21 17:37 UTC, nawel-aa commented on src/modules/base/list/list.js
> +    }
- Since the `actionclick` event is identical to the one coming from regular actions, you should use a method `dispatchActionClick(actionName)` to avoid repetition.
- If an event is dispatched at different point of a JS file, document it only once. Otherwise, it will appear twice in the doc.

2022-09-27 14:32 UTC, nawel-aa approved these changes
Looks good to me! 👌 🚀

2022-09-27 18:00 UTC, jbverger approved these changes

2022-09-27 18:00 UTC, merged