feature-ABC-966-image-compare-slider
avonni/base-components pull request #598
Opened 2023-05-23 17:24 UTC by Jusolijus17

### Features
Image
- Slide to compare two images

2023-06-05 18:03 UTC, nawel-aa requested changes
**Fixes:**
- We shouldn't see the magnifier in this pull request, since this feature was made in another branch. Please remove anything regarding the magnifier, and merge the master branch in this branch to resolve the remaining conflicts. 🙂
- Right now the tests don't pass.

**Documentation:**
- The compare attributes need to be documented. You need to add a `@typedef` block in the `image.jsdoc.js` file. See [Documenting Objects](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc) in our documentation.

**Improvements:** 
- Can you make it work on touch screens?
- Can you make it work with the keyboard?

2023-06-05 18:03 UTC, nawel-aa commented on src/modules/base/image/image.js
> +    }
It would be nice if we could click anywhere in the whole window to release.
Since you only have a property to change, the neater way to do it would be to add the listener in `handleCompareMouseDown()` and remove it inside `handleCompareMouseUp()`. You can see an example of what I mean in the flow components repo, in `propertyEditorDialogLeftPanel` > `handleObjectFieldItemMouseDown()`.

2023-06-05 20:58 UTC, Jusolijus17 commented on src/modules/base/image/image.js
> +            if (this.compareSrc !== '') {
No, we don't, because in that case, we don't want to show the compare slider with an empty compare image. That's why I ensure that `compareSrc` isn't an empty string. To simplify the code, I changed the condition from `if (this.compareSrc !== '')` to `if (this.compareSrc)`.

2023-06-08 18:48 UTC, nawel-aa requested changes
Almost there, nice keyboard support! 👌
Aside from the few comments I had, the file should be reordered in alphabetical order, per section (public properties together, private properties, private methods, event handlers).

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.html
> +                    aria-role="button"
It's `role="button"`, not `aria-role="button"`. It's my bad, I see that I wrote it wrong in the subtask. 🤦‍♀️ 
And since we're improving accessibility, may as well add: 
- [`aria-pressed`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed) to the `<div>` to indicate whether the handle is being dragged or not.
- `alternative-text` attributes to the `lightning-icons`, indicating what to do to move the cursor ("Press left to show the original image" / "Press right to show the compared image", for example?).

This is a very visual feature, so it may seem useless to make it accessible to screen readers. But as soon as we make it focusable, we can't hide it to screen readers. So we may as well explain its purpose, instead of having a mysterious toggle button. 🙂

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        } else if (this._isDraggingCompareCursor && event.target === handle) {
Why check if the event target is the handle? Since the event listener is placed directly on the handle, and nothing inside of it is focusable, it should always be the case.

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.js
> +                        compareImg.style.width = '0px';
By convention, if we can make it simpler, we do: "0px" is equal to 0. 😊

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        }
I think you can do the hover using CSS only. If `this.compareAttributes.showLabelsOnHover` is `true`, you can add a class in the `computedImageClass`, let's say `avonni-image__container_compare-labels-on-hover`. In your CSS, you can then have something like:

```
.avonni-image__container_compare-labels-on-hover .avonni-image__compare-overlay {
     display: none;
}
.avonni-image__container_compare-labels-on-hover:hover .avonni-image__compare-overlay {
     display: block;
}
```

I haven't tested it, but I'm guessing it should work. 😊

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.js
> +                }, 50);
What you actually want to do is wait for the image to be rendered. It may take less or more than 50ms, so a timeout is not ideal. What you can use is [requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) instead.

2023-06-08 18:48 UTC, nawel-aa commented on src/modules/base/image/image.js
> +    handleCompareSlider(img) {
I think this method should be named something like `initCompareSlider()`, since it is not handling an event.

2023-06-09 14:55 UTC, Jusolijus17 commented on src/modules/base/image/__examples__/compare/compare.js
> +    };
Okay, but now that I have set `originalLabel` and `compareLabel` to empty strings by default, wouldn't it be better if I assign a value to these two for demonstration purposes?

2023-06-13 12:52 UTC, nawel-aa requested changes
Your fixes are good! But I noticed a few small bugs described in more details in the task. 🙂

2023-06-13 12:52 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        compareLabel: '',
You can just remove the two keys from the default value. No need to set them to empty strings.

2023-06-14 15:34 UTC, nawel-aa requested changes

2023-06-14 18:08 UTC, nawel-aa approved these changes
Nice job, looks good to me! 🎉

2023-06-26 19:56 UTC, merged