feature-ABC-965-image-magnifier-option
avonni/base-components pull request #599
Opened 2023-05-23 17:30 UTC by Jusolijus17

### Features
Image
- Magnifier

2023-05-29 16:45 UTC, nawel-aa requested changes
Very neat subtest sections! I didn't know we could do that, and we will definitely start doing it everywhere. And overall, nice first big feature, congrats! 😃 My comments are mostly about conventions and refactoring, so good job! I only noticed one bug, that I mentioned on Jira.

Three more things on documentation and formatting:
- The properties and methods you added should be sorted in alphabetical order, and placed in each of their respective section. You can see the "File order" section in [our documentation](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019795/Javascript).
- It's a big enough feature that it deserves a story (like `Base`, `BaseSmall`, etc.) in the stories file. If you create a new story, you also have to create a new example component in `__examples__`, using exactly the same configuration as the story.
- I updated the [Confluence page](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/363593765/Image) with the new attributes and the styling hooks, but in the future, you can do it. 🙂

Two suggestion of improvements:
- Could it be easily adapted on touch screens, using [touch events](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#touch_event_types)? Otherwise, it will be another task.
- The functions used only for the magnifier can be extracted in another javascript file (`autoPositionMagnifier()`, `standardMagnifier()`, etc.).

2023-05-29 16:45 UTC, nawel-aa commented on src/modules/base/image/__tests__/image.test.js
> +                'avonni-image_float-left'
Instead of using `split()` on `className` you can use `container.classList.toContain()`. If you are using this strategy (only testing if the specific class is added), you don't need to check if `avonni-image` has been added, since it is always present. The advantage of using `className` over `classList`, is that we are sure that exactly these classes are present, and not one more.

2023-05-29 16:45 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        return classSet('avonni-image avonni-image_container')
You don't need to add `avonni-image_container`, you can use the already existing `avonni-image` (or rename it), and add the new CSS you need to it.

2023-05-29 16:45 UTC, nawel-aa commented on src/modules/base/image/__tests__/image.test.js
> +            element.src = src;
If you really want to test the magnifier mouse move, you can add a `clientX` and `clientY` position to the `mousemove` event, and mock the implementation of `getBoundingClientRect()` on the image. Otherwise, you are not really testing the magnifier, just that something happens when we hover the image.

For an example of what I mean, you can checkout "Pill container: reorder event, from single-line collapsed popover to visible pill" in `pillContainer.test.js`. You'll see the mocked implementation of `getBoundingClientRect()` on `items[0]` and the custom event `clientX` setting.

2023-05-29 18:41 UTC, Jusolijus17 commented on src/modules/base/image/image.js
> +    default: 'none'
I decided to add the `none` option because you cannot deselect an option after choosing one from the drop-down menu. So, if you mistakenly clicked on `standard`, you wouldn't be able to disable the magnifier afterwards by reselecting `Choose an option...`. You would need a `none` option or an on/off switch for the magnifier.

2023-05-29 18:55 UTC, nawel-aa commented on src/modules/base/image/image.js
> +    default: 'none'
You can add a "none" option to the Storybook `magnifierType` argument options, if you want.
Storybook is only used during the development process, to make it easier to test what we're doing. In practice, the magnifier type will be passed by a parent component (through an HTML `magnifier-type` attribute, same as you do it in the storybook wrapper). And when we will display this option in our own property editor, in Salesforce, we will use our combobox, where we can clear the selected value: 

<img width="246" alt="Screenshot 2023-05-29 at 14 52 54" src="https://github.com/avonni/base-components/assets/71400095/5354d26c-587b-4ab6-a839-d0b44621578d">

2023-05-30 15:49 UTC, Jusolijus17 commented on src/modules/base/image/image.css
> +.avonni-image_magnifier {
I changed most of the custom classes to slds classes, but I feel like adding and removing a class (`slds-hide` and `slds-show`) each time only to show and hide an element is more complicated than simply using `element.style.display = 'block/none'`. Let me know what you think.

2023-06-01 15:10 UTC, nawel-aa requested changes
Really nice job, I have nothing to add! 👌
My comments are documentation related. Aside from these 3-minute fixes, it's good to go!

2023-06-01 15:10 UTC, nawel-aa commented on src/modules/base/image/image.html
>                  style={computedMagnifiedImgStyle}
I hadn't seen this `alt`, but it's a good idea to [make the magnifier invisible to screen readers](https://www.w3.org/WAI/tutorials/images/decorative/), by giving it an empty `alt=""`.
Unless you think it's useful to show it to screen readers, in which case I would add an `alternativeText` key to the `magnifier-attributes`.

2023-06-02 19:37 UTC, nawel-aa approved these changes
🚀

2023-06-05 13:23 UTC, merged