Bugfix abc 984 image magnifier option
avonni/base-components pull request #609
Opened 2023-06-15 15:39 UTC by Jusolijus17

### Fixes
**Image**
- Fixing small issues

2023-06-15 18:46 UTC, nawel-aa requested changes
One of the tests is failing. Can you check if it should still pass, or update it otherwise?

2023-06-21 18:28 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        }
Here it is impossible to reset the `zoomFactor` and the `smoothMove` keys. If magnifier attributes were passed, and then removed, their value would remain.

2023-06-21 19:35 UTC, nawel-aa requested changes

2023-06-21 19:35 UTC, nawel-aa commented on src/modules/base/image/image.css
> +    border-radius: var(--avonni-image-magnifier-radius-border, 0);
Good idea! But if you add a styling hook, you need to document it in `image.jsdoc.js` and [Confluence](https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/363593765/Image). 😊

2023-06-21 19:38 UTC, Jusolijus17 commented on src/modules/base/image/image.css
> +    border-radius: var(--avonni-image-magnifier-radius-border, 0);
Yes I remembered right after requesting your review🤦‍♂️

2023-06-21 19:44 UTC, nawel-aa approved these changes

2023-06-22 14:08 UTC, merged