[fix] (ABC-992): fixed compare img height
avonni/base-components pull request #616
Opened 2023-06-27 03:05 UTC by Jusolijus17

### Fixes
**Image**
- Compare slider

2023-06-28 16:37 UTC, nawel-aa requested changes

2023-06-28 16:37 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        styleProperties['object-fit'] = this.cropFit ? this.cropFit : null;
1. Do you _need_ to set the properties to `null` or could you juste set them to whatever falsy value the property contains (`undefined`, `null`, `''`)?
2. Your choice to decide if it is easier to read or not, but these ternary operator lines can be simplified into `styleProperties['object-fit'] = this.cropFit || null;`

2023-06-28 16:37 UTC, nawel-aa commented on src/modules/base/image/image.js
> +        }
1. You can definitely refactor this big block into one line for each property. Something like:
`styleProperties['min-width'] = this.staticImages && this.width ? this.width : null;`
2. If there is a public property (`this.width`), we use it instead of the private property (`this._width`). Unless we want to set it, of course, then we set the private property. It makes it clearer that the public property exists, and it is in case there is some computation done in the `get propertyName()`.

2023-06-28 16:37 UTC, nawel-aa commented on src/modules/base/image/image.js
> +            : 'flex-direction: column;';
You can use an [SLDS class](https://www.lightningdesignsystem.com/utilities/grid/#Top-to-Bottom) toggle for this, instead of a custom style.

2023-06-28 16:44 UTC, nawel-aa reviewed
I forgot to mention it, but one test is also broken. :)

2023-06-29 13:30 UTC, nawel-aa approved these changes
🎉

2023-06-29 13:34 UTC, jbverger approved these changes

2023-06-29 13:35 UTC, merged