[feat](ABC-1030): Create Avonni Focus Trap component
avonni/base-components pull request #651
Opened 2023-08-10 18:32 UTC by Hubert06

2023-08-14 19:38 UTC, nawel-aa requested changes
My comments mostly concern the fact that the component won't be publicly available in its current state. Aside from that it works well in all the base components that use it.

2023-08-14 19:38 UTC, nawel-aa commented on src/modules/base/focusTrap/__tests__/focusTrap.test.js
I think it's fairly doable to add tests. :)

2023-08-14 19:38 UTC, nawel-aa commented on lwc.config.json
> +        },
To make the component available publicly, you need to add the same lines with `avonni/focusTrap`, and add it to the `expose `array at the end of the file.

2023-08-14 19:38 UTC, nawel-aa commented on src/modules/base/focusTrap/__requirements__/requirements.md
If we want this file to appear in [our documentation](https://www.avonnicomponents.com/), it needs to be placed in a `__docs__` folder, and renamed `focusTrap.md`.
A level 3 title should also be added on the first line (for example `### Requirements`), for more consistency.

2023-08-14 19:38 UTC, nawel-aa commented on src/modules/base/focusTrap/focusTrap.js
> +
To make the component appear in [our documentation](https://www.avonnicomponents.com/), you need to add a [class JSDoc comment](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1888616449/Javascript+documentation+JSDoc#Allowed-block-tags-for-classes) with a `@public` tag. In your case, you won't have a `@storyId`, since there is no storybook example for this component.

2023-08-14 19:38 UTC, nawel-aa commented on src/modules/base/focusTrap/focusTrap.js
> +     */
This JSDoc comment needs to have a `@public` tag for the method to appear in our doc.

2023-08-14 19:38 UTC, nawel-aa commented on src/modules/base/focusTrap/focusTrap.js
> +    }
Our conventions are all mixed up now that we are working on several repos. 😊
But you probably should follow one of those two conventions when naming your methods and properties:
- The **base components** convention, where we never use a `_` in the name of a method, and use a `_` in the name of a property only if it is not called in the HTML.
- The **flow screen components** convention, where we use a `_` in the name of the methods and properties that are not called in the HTML.

2023-08-16 14:54 UTC, Hubert06 commented on src/modules/base/focusTrap/__tests__/focusTrap.test.js
I added some tests. Could not figure out how to add elements inside the slot in the tests, so they are really basic and just for good measure.

2023-08-16 15:04 UTC, nawel-aa approved these changes
All good! 👌

2023-08-16 21:03 UTC, jbverger approved these changes

2023-08-25 19:46 UTC, jbverger approved these changes

2023-08-25 19:46 UTC, merged