(feat) (abc 201) input counter type attribute
avonni/base-components pull request #79
Opened 2021-06-10 17:46 UTC by AlainRusnov

Added ‘type’ property (string): 

- ‘number’, ‘currency’, ‘percent’ ( ‘number’ default and ‘percent’ not percent-fixed )

Added ‘input-step’ property (number):  

- Granularity of the value - precision of significant numbers ( specified as a positive floating point number. ex: 0.01 formats the value to 2 digits after the decimal  ). Default: 0.01 in storybook

Added handler for loss of precision when inc/dec value. Passes step validation.

When Max-Min are called on and there is a validation error, the value looses its formatting ( e.g. currency or % sign ), until it meets the criteria.

Tests : type, input-step, precision

2021-06-17 14:35 UTC, jbverger requested changes

2021-06-17 14:35 UTC, jbverger commented on src/modules/base/inputCounter/inputCounter.js
> +        this._min = typeof min === 'number' ? min : '';
If _min is a number, default value should be null?

2021-06-17 14:35 UTC, jbverger commented on src/modules/base/inputCounter/inputCounter.html
> +                autocomplete="off"
autocomplete is not available for type==number.
_Use this attribute with email, search, tel, text, and url input types only_ https://developer.salesforce.com/docs/component-library/bundle/lightning-input/specification

2021-06-17 14:35 UTC, jbverger commented on src/modules/base/inputCounter/inputCounter.js
> +        : this.step.toString().includes('.' || ',') ? 0.1
No need to manage that case. If the step include decimal, the user need to specify a fractionDigits. Same as lightning-input, the user need to specify a step for decimal value.

2021-06-17 15:47 UTC, nawel-aa requested changes

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.css
> +    padding-top: 5px;
You can probably use `.slds-p-top_xx-small` on the element instead of a custom CSS rule.

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.html
> +                autocomplete="off"
<img width="1190" alt="Screen Shot 2021-06-17 at 11 15 51 AM" src="https://user-images.githubusercontent.com/71400095/122425306-63e82b00-cf5d-11eb-8197-7361f34e481c.png">

But when we remove it, the browser adds a form autocomplete. 😕

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.js
> +            this.max? this.handlePrecision(this.max) : null;
We try to pass eslint validation as much as possible, even if it means writing less cool looking code. 😄 
So instead of ternary operators, you should use `if (this.max) this.handlePrecision(this.max);`

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.js
> +            if (this.value !== undefined && !isNaN(this.value)) {
You can probably just check if `!isNaN(this.value)`, since `!isNaN(undefined)` will return false?

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.js
> +            this.step = this.handlePrecision(this.step);
Same as above, unless there's a specific reason for not doing it, you should assign new values to `this._step` instead of `this.step`.

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.js
> +                if (this.min || this.min === 0) {
Is there a value in having `this.value = this.value` ? If not, the block could probably be changed into:
```
if ((this.min || this.min === 0) && (this.value - this.step < this.min)) {
  this._value = this.min;
}
```

2021-06-17 15:47 UTC, nawel-aa commented on src/modules/base/inputCounter/inputCounter.js
> +        let validationMsg = this._constraint.reportValidity((message) => {
I am not sure why you use helpMsg. You can probably just return the result of `this._constraint.reportValidity(...)` and assign the message to `this.helpMessage` inside of it (same as what have been done in dualListbox).

2021-07-22 12:57 UTC, jbverger approved these changes

2021-07-22 12:58 UTC, merged