(feat) (abc 243) list component actions display
avonni/base-components pull request #94
Opened 2021-06-18 15:53 UTC by AlainRusnov

List actions : 
- 1 action no label : button-icon
- 1 action label : button
- multi actions : button menu

2021-06-21 13:53 UTC, jbverger requested changes

2021-06-22 14:19 UTC, nawel-aa requested changes
There's a small HTML syntax problem, but most importantly, there are no tests for the actions attribute.

2021-06-22 14:19 UTC, nawel-aa commented on src/modules/base/list/list.html
> +                        <template if:false={multiActions}>
You should not have two `template if` one inside each other, it's better to keep your logic inside your Javascript file (see [guidelines](https://avonnicreator.atlassian.net/wiki/spaces/LDG/pages/1587019781/HTML+Templates)).
Maybe you could use only`if:false={multiActions}`, and add a `if:true={actions.length}` to your `<div>` line 128, to handle the case of empty actions?

2021-06-25 12:18 UTC, jbverger commented on src/modules/base/list/list.js
> +    get multiActions() {
Rename multiActions to hasMultipleActions

2021-06-25 12:18 UTC, jbverger commented on src/modules/base/list/list.js
> +    get singleAction() {
Rename singleAction to firstAction.

2021-06-25 17:54 UTC, jbverger approved these changes

2021-06-25 17:55 UTC, merged